#!/usr/bin/env bash
# VideoMind — Batch 1
# Click-to-seek · Exports · Duration · Public share links
# Run from /home/probeat/videomind

set -e
ROOT="$(pwd)"
FE="$ROOT/frontend"
BE="$ROOT/backend"

if [ ! -d "$FE" ] || [ ! -d "$BE" ]; then
  echo "❌ Run from the project root (/home/probeat/videomind)"
  exit 1
fi

mkdir -p "$FE/src/app/v/[id]"
mkdir -p "$FE/src/lib"
mkdir -p "$FE/src/components/video"

echo "🚀 Batch 1 starting..."
echo ""

# ═════════════════════════════════════════════════════════════════════════════
# 1. EXPORT UTILITIES  (frontend/src/lib/exports.ts)
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/lib/exports.ts" << 'EOF'
// src/lib/exports.ts
// Generate downloadable transcript formats entirely in the browser.

export interface Segment { start: number; end: number; text: string; }

interface ExportVideo {
  title: string;
  summary?: string;
  chapters?: Array<{ title: string; startSeconds: number; summary: string }>;
  highlights?: Array<{ startSeconds: number; endSeconds: number; reason: string; text: string }>;
  tags?: string[];
  transcript?: Segment[];
}

// ── Time formatters ─────────────────────────────────────────────────────────
function pad(n: number, size = 2) { return String(Math.floor(n)).padStart(size, "0"); }

/** 00:01:23,456 — SRT uses a comma before milliseconds */
function srtTime(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec - Math.floor(sec)) * 1000);
  return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms, 3)}`;
}

/** 00:01:23.456 — WebVTT uses a period before milliseconds */
function vttTime(sec: number): string {
  return srtTime(sec).replace(",", ".");
}

/** 1:23 — human readable */
export function readableTime(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${pad(s)}`;
}

// ── Format builders ─────────────────────────────────────────────────────────

export function toSRT(segments: Segment[]): string {
  return segments
    .map((seg, i) =>
      `${i + 1}\n${srtTime(seg.start)} --> ${srtTime(seg.end)}\n${seg.text}\n`
    )
    .join("\n");
}

export function toVTT(segments: Segment[]): string {
  const body = segments
    .map((seg) => `${vttTime(seg.start)} --> ${vttTime(seg.end)}\n${seg.text}\n`)
    .join("\n");
  return `WEBVTT\n\n${body}`;
}

export function toMarkdown(video: ExportVideo): string {
  const lines: string[] = [];

  lines.push(`# ${video.title}\n`);

  if (video.tags?.length) {
    lines.push(`**Tags:** ${video.tags.join(", ")}\n`);
  }

  if (video.summary) {
    lines.push(`## Summary\n\n${video.summary}\n`);
  }

  if (video.chapters?.length) {
    lines.push(`## Chapters\n`);
    video.chapters.forEach((ch, i) => {
      lines.push(`### ${i + 1}. ${ch.title} — \`${readableTime(ch.startSeconds)}\`\n`);
      lines.push(`${ch.summary}\n`);
    });
  }

  if (video.highlights?.length) {
    lines.push(`## Highlights\n`);
    video.highlights.forEach((hl) => {
      lines.push(`> **${hl.reason}** — \`${readableTime(hl.startSeconds)}\``);
      lines.push(`>`);
      lines.push(`> ${hl.text}\n`);
    });
  }

  if (video.transcript?.length) {
    lines.push(`## Full Transcript\n`);
    video.transcript.forEach((seg) => {
      lines.push(`\`${readableTime(seg.start)}\` ${seg.text}`);
    });
    lines.push("");
  }

  lines.push(`---\n`);
  lines.push(`*Generated by [VideoMind](https://vidzmind.xyz) — AI video intelligence on Shelby Protocol*`);

  return lines.join("\n");
}

export function toPlainText(segments: Segment[]): string {
  return segments.map((s) => s.text).join(" ");
}

// ── Download trigger ────────────────────────────────────────────────────────
export function downloadFile(content: string, filename: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Slugify a title for use as a filename */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "transcript";
}
EOF
echo "✅ frontend/src/lib/exports.ts"

# ═════════════════════════════════════════════════════════════════════════════
# 2. EXPORT MENU COMPONENT
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/ExportMenu.tsx" << 'EOF'
"use client";
import { useState, useRef, useEffect } from "react";
import { Download, FileText, Captions, FileCode, ChevronDown, CheckCircle } from "lucide-react";
import { clsx } from "clsx";
import {
  toSRT, toVTT, toMarkdown, toPlainText, downloadFile, slugify,
  type Segment,
} from "@/lib/exports";

interface ExportMenuProps {
  title: string;
  transcript?: Segment[];
  summary?: string;
  chapters?: Array<{ title: string; startSeconds: number; summary: string }>;
  highlights?: Array<{ startSeconds: number; endSeconds: number; reason: string; text: string }>;
  tags?: string[];
}

export function ExportMenu(props: ExportMenuProps) {
  const { title, transcript } = props;
  const [open, setOpen] = useState(false);
  const [done, setDone] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handler(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  if (!transcript?.length) return null;

  const slug = slugify(title);

  const flash = (label: string) => {
    setDone(label);
    setTimeout(() => setDone(null), 2000);
    setOpen(false);
  };

  const OPTIONS = [
    {
      key: "srt",
      label: "Subtitles (.srt)",
      hint: "For video editors & players",
      icon: Captions,
      run: () => { downloadFile(toSRT(transcript), `${slug}.srt`, "text/plain"); flash("srt"); },
    },
    {
      key: "vtt",
      label: "WebVTT (.vtt)",
      hint: "For web video players",
      icon: Captions,
      run: () => { downloadFile(toVTT(transcript), `${slug}.vtt`, "text/vtt"); flash("vtt"); },
    },
    {
      key: "md",
      label: "Full notes (.md)",
      hint: "Summary, chapters, highlights & transcript",
      icon: FileCode,
      run: () => { downloadFile(toMarkdown(props), `${slug}.md`, "text/markdown"); flash("md"); },
    },
    {
      key: "txt",
      label: "Plain text (.txt)",
      hint: "Transcript only, no timestamps",
      icon: FileText,
      run: () => { downloadFile(toPlainText(transcript), `${slug}.txt`, "text/plain"); flash("txt"); },
    },
  ];

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-dark-700 border border-white/10 text-xs font-syne font-semibold text-white/60 hover:text-white hover:border-white/20 transition-all"
      >
        {done
          ? <><CheckCircle size={12} className="text-volt" /> Downloaded</>
          : <><Download size={12} /> Export</>
        }
        <ChevronDown size={11} className={clsx("transition-transform", open && "rotate-180")} />
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-2 w-64 glass-card rounded-xl overflow-hidden z-40 shadow-xl shadow-black/40">
          <div className="px-4 py-2.5 border-b border-white/[0.06]">
            <p className="text-[10px] font-mono text-white/30 uppercase tracking-widest">
              Export transcript
            </p>
          </div>
          {OPTIONS.map(({ key, label, hint, icon: Icon, run }) => (
            <button
              key={key}
              onClick={run}
              className="w-full flex items-start gap-3 px-4 py-3 text-left hover:bg-white/[0.04] transition-all border-b border-white/[0.03] last:border-0"
            >
              <Icon size={13} className="text-volt/60 shrink-0 mt-0.5" />
              <div className="min-w-0">
                <p className="text-xs font-dm text-white/80">{label}</p>
                <p className="text-[10px] font-mono text-white/25 mt-0.5">{hint}</p>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
EOF
echo "✅ frontend/src/components/video/ExportMenu.tsx"

# ═════════════════════════════════════════════════════════════════════════════
# 3. VIDEO PLAYER — forwardRef with seekTo + duration capture
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/VideoPlayer.tsx" << 'EOF'
"use client";
import {
  useState, useRef, useEffect,
  forwardRef, useImperativeHandle,
} from "react";
import {
  Play, Pause, Volume2, VolumeX, Maximize,
  Loader2, AlertTriangle, Film, ExternalLink,
} from "lucide-react";
import { clsx } from "clsx";

export interface VideoPlayerHandle {
  seekTo: (seconds: number) => void;
  getCurrentTime: () => number;
}

interface VideoPlayerProps {
  streamUrl: string | null;
  title: string;
  shelbyAddress?: string;
  blobName?: string;
  /** Called once when metadata loads, with the video duration in seconds */
  onDuration?: (seconds: number) => void;
  /** Called on every timeupdate — used to highlight the active transcript line */
  onTimeUpdate?: (seconds: number) => void;
}

export const VideoPlayer = forwardRef<VideoPlayerHandle, VideoPlayerProps>(
  function VideoPlayer(
    { streamUrl, shelbyAddress, onDuration, onTimeUpdate },
    ref
  ) {
    const videoRef = useRef<HTMLVideoElement>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(false);
    const [playing, setPlaying] = useState(false);
    const [muted, setMuted] = useState(false);
    const [progress, setProgress] = useState(0);
    const [duration, setDuration] = useState(0);
    const [currentTime, setCurrentTime] = useState(0);
    const [showControls, setShowControls] = useState(true);
    const hideTimer = useRef<ReturnType<typeof setTimeout>>();
    const durationSent = useRef(false);

    // Expose seekTo / getCurrentTime to the parent page
    useImperativeHandle(ref, () => ({
      seekTo: (seconds: number) => {
        const v = videoRef.current;
        if (!v) return;
        v.currentTime = seconds;
        v.play().catch(() => {});
        setPlaying(true);
        // Scroll player into view so the user sees the jump
        v.scrollIntoView({ behavior: "smooth", block: "center" });
      },
      getCurrentTime: () => videoRef.current?.currentTime ?? 0,
    }));

    const resetHideTimer = () => {
      if (hideTimer.current) clearTimeout(hideTimer.current);
      setShowControls(true);
      hideTimer.current = setTimeout(() => { if (playing) setShowControls(false); }, 3000);
    };

    useEffect(() => () => { if (hideTimer.current) clearTimeout(hideTimer.current); }, []);

    function togglePlay() {
      const v = videoRef.current;
      if (!v) return;
      if (v.paused) { v.play(); setPlaying(true); }
      else { v.pause(); setPlaying(false); }
      resetHideTimer();
    }

    function toggleMute() {
      const v = videoRef.current;
      if (!v) return;
      v.muted = !v.muted;
      setMuted(v.muted);
    }

    function toggleFullscreen() {
      const v = videoRef.current;
      if (!v) return;
      if (document.fullscreenElement) document.exitFullscreen();
      else v.requestFullscreen();
    }

    function handleTimeUpdate() {
      const v = videoRef.current;
      if (!v) return;
      setCurrentTime(v.currentTime);
      setProgress(v.duration ? (v.currentTime / v.duration) * 100 : 0);
      onTimeUpdate?.(v.currentTime);
    }

    function handleLoadedMetadata() {
      const v = videoRef.current;
      if (!v) return;
      setDuration(v.duration);
      // Report duration to the parent exactly once
      if (!durationSent.current && v.duration && isFinite(v.duration)) {
        durationSent.current = true;
        onDuration?.(v.duration);
      }
    }

    function seek(e: React.MouseEvent<HTMLDivElement>) {
      const v = videoRef.current;
      if (!v || !v.duration) return;
      const rect = e.currentTarget.getBoundingClientRect();
      const pct = (e.clientX - rect.left) / rect.width;
      v.currentTime = pct * v.duration;
    }

    function fmt(s: number) {
      if (!s || isNaN(s)) return "0:00";
      const h = Math.floor(s / 3600);
      const m = Math.floor((s % 3600) / 60);
      const sec = Math.floor(s % 60);
      if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}`;
      return `${m}:${String(sec).padStart(2, "0")}`;
    }

    if (!streamUrl) {
      return (
        <div className="aspect-video rounded-2xl bg-dark-800 border border-white/[0.06] flex flex-col items-center justify-center gap-4">
          <Film size={40} className="text-white/10" strokeWidth={1} />
          <p className="text-white/30 text-sm font-mono">Video stream unavailable</p>
        </div>
      );
    }

    return (
      <div
        className="relative aspect-video rounded-2xl overflow-hidden bg-black border border-white/[0.06] group"
        onMouseMove={resetHideTimer}
        onMouseLeave={() => playing && setShowControls(false)}
      >
        {loading && !error && (
          <div className="absolute inset-0 flex items-center justify-center bg-dark-950/80 z-10">
            <div className="flex flex-col items-center gap-3">
              <Loader2 size={28} className="text-volt animate-spin" />
              <p className="text-xs font-mono text-white/40">Loading from Shelby...</p>
            </div>
          </div>
        )}

        {error && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 bg-dark-950/90 z-10 px-6 text-center">
            <AlertTriangle size={28} className="text-red-400" />
            <div>
              <p className="text-sm text-white/60 font-dm mb-1">Could not load video from Shelby</p>
              <p className="text-xs text-white/30 font-mono">The blob may have expired — try renewing it</p>
            </div>
            <a
              href={streamUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2 rounded-lg border border-volt/20 bg-volt/5 text-volt text-xs font-mono hover:bg-volt/10 transition-all"
            >
              <ExternalLink size={12} /> Open direct URL
            </a>
          </div>
        )}

        <video
          ref={videoRef}
          src={streamUrl}
          className="w-full h-full object-contain"
          preload="metadata"
          onClick={togglePlay}
          onLoadStart={() => setLoading(true)}
          onCanPlay={() => setLoading(false)}
          onLoadedMetadata={handleLoadedMetadata}
          onTimeUpdate={handleTimeUpdate}
          onPlay={() => setPlaying(true)}
          onPause={() => setPlaying(false)}
          onError={() => { setError(true); setLoading(false); }}
          onEnded={() => setPlaying(false)}
        />

        {/* Controls */}
        <div className={clsx(
          "absolute inset-x-0 bottom-0 transition-all duration-300 z-20",
          showControls || !playing ? "opacity-100 translate-y-0" : "opacity-0 translate-y-2"
        )}>
          <div className="h-24 bg-gradient-to-t from-black/80 to-transparent absolute inset-x-0 bottom-0 pointer-events-none" />
          <div className="relative px-4 pb-4 pt-8 space-y-2">
            <div className="h-1 bg-white/20 rounded-full cursor-pointer group/bar" onClick={seek}>
              <div className="h-full progress-bar rounded-full relative transition-all" style={{ width: `${progress}%` }}>
                <div className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-3 bg-volt rounded-full shadow-lg opacity-0 group-hover/bar:opacity-100 transition-opacity" />
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <button
                  onClick={togglePlay}
                  className="w-8 h-8 rounded-lg bg-volt/10 hover:bg-volt/20 border border-volt/20 flex items-center justify-center transition-all"
                >
                  {playing ? <Pause size={14} className="text-volt" /> : <Play size={14} className="text-volt ml-0.5" />}
                </button>
                <button onClick={toggleMute} className="text-white/40 hover:text-white transition-colors">
                  {muted ? <VolumeX size={14} /> : <Volume2 size={14} />}
                </button>
                <span className="font-mono text-xs text-white/40">
                  {fmt(currentTime)} / {fmt(duration)}
                </span>
              </div>

              <div className="flex items-center gap-3">
                {shelbyAddress && (
                  <a
                    href={`https://explorer.shelby.xyz/testnet/accounts/${shelbyAddress}`}
                    target="_blank" rel="noopener noreferrer"
                    className="flex items-center gap-1 px-2 py-1 rounded bg-volt/10 border border-volt/20 hover:bg-volt/20 transition-all"
                  >
                    <span className="font-mono text-[10px] text-volt">⚡ Shelby</span>
                  </a>
                )}
                <button onClick={toggleFullscreen} className="text-white/40 hover:text-white transition-colors">
                  <Maximize size={14} />
                </button>
              </div>
            </div>
          </div>
        </div>

        {!playing && !loading && !error && (
          <button onClick={togglePlay} className="absolute inset-0 flex items-center justify-center z-10">
            <div className="w-16 h-16 rounded-full bg-volt/20 border border-volt/30 backdrop-blur-sm flex items-center justify-center hover:bg-volt/30 transition-all">
              <Play size={24} className="text-volt ml-1" />
            </div>
          </button>
        )}
      </div>
    );
  }
);
EOF
echo "✅ frontend/src/components/video/VideoPlayer.tsx  (forwardRef + seekTo + duration)"

# ═════════════════════════════════════════════════════════════════════════════
# 4. TRANSCRIPT PANEL — clickable, auto-highlights active segment
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/TranscriptPanel.tsx" << 'EOF'
"use client";
import { useRef, useEffect } from "react";
import { FileText, Search } from "lucide-react";
import { clsx } from "clsx";
import { useState } from "react";
import type { Segment } from "@/lib/exports";
import { readableTime } from "@/lib/exports";

interface TranscriptPanelProps {
  transcript: Segment[];
  currentTime: number;
  onSeek: (seconds: number) => void;
}

export function TranscriptPanel({ transcript, currentTime, onSeek }: TranscriptPanelProps) {
  const [query, setQuery] = useState("");
  const activeRef = useRef<HTMLButtonElement>(null);
  const [autoScroll, setAutoScroll] = useState(true);

  // Index of the segment currently playing
  const activeIdx = transcript.findIndex(
    (seg) => currentTime >= seg.start && currentTime < seg.end
  );

  // Keep the active line in view (only when not searching, and if enabled)
  useEffect(() => {
    if (!autoScroll || query) return;
    activeRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIdx, autoScroll, query]);

  const filtered = query.trim()
    ? transcript
        .map((seg, i) => ({ seg, i }))
        .filter(({ seg }) => seg.text.toLowerCase().includes(query.toLowerCase()))
    : transcript.map((seg, i) => ({ seg, i }));

  return (
    <div className="glass-card rounded-2xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-3 p-4 border-b border-white/[0.06]">
        <FileText size={14} className="text-white/40 shrink-0" />
        <p className="text-sm font-syne font-semibold text-white shrink-0">Transcript</p>

        {/* Inline search */}
        <div className="relative flex-1 max-w-[200px] ml-auto">
          <Search size={11} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-white/25" />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search..."
            className="w-full bg-dark-800 border border-white/[0.06] rounded-lg pl-7 pr-2 py-1.5 text-[11px] text-white placeholder-white/20 font-dm focus:outline-none focus:border-volt/30 transition-all"
          />
        </div>

        <span className="font-mono text-[10px] text-white/20 shrink-0">
          {query ? `${filtered.length} found` : `${transcript.length} lines`}
        </span>
      </div>

      {/* Auto-scroll toggle */}
      {!query && (
        <div className="px-4 py-2 border-b border-white/[0.04] flex items-center justify-between">
          <p className="text-[10px] font-mono text-white/20">
            Click any line to jump to that moment
          </p>
          <button
            onClick={() => setAutoScroll((v) => !v)}
            className={clsx(
              "text-[10px] font-mono transition-colors",
              autoScroll ? "text-volt/60 hover:text-volt" : "text-white/20 hover:text-white/40"
            )}
          >
            {autoScroll ? "● Auto-scroll on" : "○ Auto-scroll off"}
          </button>
        </div>
      )}

      {/* Segments */}
      <div className="max-h-80 overflow-y-auto p-2">
        {filtered.length === 0 && (
          <p className="text-center py-8 text-xs text-white/25 font-mono">
            No lines match "{query}"
          </p>
        )}

        {filtered.map(({ seg, i }) => {
          const active = i === activeIdx && !query;
          return (
            <button
              key={i}
              ref={active ? activeRef : undefined}
              onClick={() => onSeek(seg.start)}
              className={clsx(
                "w-full flex items-start gap-3 px-3 py-2 rounded-lg text-left transition-all group",
                active
                  ? "bg-volt/[0.08] border border-volt/20"
                  : "border border-transparent hover:bg-white/[0.03]"
              )}
            >
              <span className={clsx(
                "font-mono text-[10px] shrink-0 mt-0.5 w-11 text-right tabular-nums transition-colors",
                active ? "text-volt" : "text-volt/40 group-hover:text-volt/70"
              )}>
                {readableTime(seg.start)}
              </span>
              <p className={clsx(
                "text-sm font-dm leading-relaxed transition-colors",
                active ? "text-white" : "text-white/50 group-hover:text-white/80"
              )}>
                {seg.text}
              </p>
            </button>
          );
        })}
      </div>
    </div>
  );
}
EOF
echo "✅ frontend/src/components/video/TranscriptPanel.tsx  (click-to-seek + search)"

# ═════════════════════════════════════════════════════════════════════════════
# 5. INSIGHTS PANEL — clickable chapters & highlights
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/InsightsPanel.tsx" << 'EOF'
"use client";
import { useState } from "react";
import {
  BookOpen, Zap, FileText, Twitter, AlignLeft,
  Tag, Clock, Copy, CheckCircle, Play,
} from "lucide-react";
import { clsx } from "clsx";
import type { VideoRecord } from "@/lib/api";
import { readableTime } from "@/lib/exports";

type Tab = "summary" | "chapters" | "highlights" | "blog" | "thread";

const TABS: Array<{ key: Tab; label: string; icon: React.ComponentType<any> }> = [
  { key: "summary",    label: "Summary",    icon: AlignLeft },
  { key: "chapters",  label: "Chapters",   icon: BookOpen },
  { key: "highlights",label: "Highlights", icon: Zap },
  { key: "blog",      label: "Blog Post",  icon: FileText },
  { key: "thread",    label: "X Thread",   icon: Twitter },
];

function CopyButton({ text, label = "Copy" }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      onClick={copy}
      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-dark-700 border border-white/10 text-xs font-mono text-white/50 hover:text-white hover:border-white/20 transition-all"
    >
      {copied
        ? <><CheckCircle size={11} className="text-volt" /> Copied!</>
        : <><Copy size={11} /> {label}</>}
    </button>
  );
}

interface InsightsPanelProps {
  video: VideoRecord;
  /** Jump the video player to a timestamp */
  onSeek?: (seconds: number) => void;
}

export function InsightsPanel({ video, onSeek }: InsightsPanelProps) {
  const [tab, setTab] = useState<Tab>("summary");
  const ai = video.ai;
  if (!ai) return null;

  const seekable = typeof onSeek === "function";

  return (
    <div className="glass-card rounded-2xl overflow-hidden">
      {/* Tabs */}
      <div className="flex overflow-x-auto border-b border-white/[0.06] px-2 scrollbar-hide">
        {TABS.map(({ key, label, icon: Icon }) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            className={clsx(
              "flex items-center gap-2 px-4 py-3.5 text-xs font-mono whitespace-nowrap border-b-2 transition-all shrink-0",
              tab === key
                ? "border-volt text-volt"
                : "border-transparent text-white/30 hover:text-white/60"
            )}
          >
            <Icon size={12} />
            {label}
          </button>
        ))}
      </div>

      <div className="p-5">
        {/* ── Summary ── */}
        {tab === "summary" && (
          <div className="space-y-4">
            <p className="text-sm text-white/70 font-dm leading-relaxed">
              {ai.summary ?? "No summary available."}
            </p>
            {ai.summary && <CopyButton text={ai.summary} label="Copy summary" />}
            {ai.tags && ai.tags.length > 0 && (
              <div className="flex items-start gap-2 pt-2 border-t border-white/[0.06]">
                <Tag size={12} className="text-white/30 mt-1 shrink-0" />
                <div className="flex flex-wrap gap-1.5">
                  {ai.tags.map((tag) => (
                    <span key={tag} className="px-2.5 py-1 rounded-lg bg-dark-700 border border-white/[0.06] text-xs font-mono text-white/40">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── Chapters (clickable) ── */}
        {tab === "chapters" && (
          <div className="space-y-1">
            {(ai.chapters ?? []).length === 0 && (
              <p className="text-white/30 text-sm py-4 text-center">No chapters available.</p>
            )}
            {(ai.chapters ?? []).map((ch, i) => (
              <button
                key={i}
                onClick={() => seekable && onSeek!(ch.startSeconds)}
                disabled={!seekable}
                className={clsx(
                  "w-full flex items-start gap-3 p-3.5 rounded-xl text-left transition-all group",
                  seekable ? "hover:bg-volt/[0.05] cursor-pointer" : "cursor-default"
                )}
              >
                <div className="flex items-center gap-2 shrink-0 mt-0.5">
                  <span className="font-mono text-xs text-white/20 w-5 text-right">{i + 1}</span>
                  <div className="w-px h-8 chapter-line" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="text-sm font-syne font-semibold text-white group-hover:text-volt transition-colors">
                      {ch.title}
                    </p>
                    <div className="flex items-center gap-1 text-[10px] font-mono text-volt/60">
                      <Clock size={9} />
                      {readableTime(ch.startSeconds)}
                    </div>
                  </div>
                  <p className="text-xs text-white/40 font-dm mt-1 leading-relaxed">{ch.summary}</p>
                </div>
                {seekable && (
                  <div className="shrink-0 mt-1 w-6 h-6 rounded-lg bg-volt/10 border border-volt/20 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                    <Play size={10} className="text-volt ml-0.5" />
                  </div>
                )}
              </button>
            ))}
          </div>
        )}

        {/* ── Highlights (clickable) ── */}
        {tab === "highlights" && (
          <div className="space-y-3">
            {(ai.highlights ?? []).length === 0 && (
              <p className="text-white/30 text-sm py-4 text-center">No highlights available.</p>
            )}
            {(ai.highlights ?? []).map((hl, i) => (
              <div key={i} className="p-4 rounded-xl bg-volt/[0.04] border border-volt/10 space-y-2.5 group">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center gap-2">
                    <Zap size={12} className="text-volt" />
                    <span className="text-xs font-mono text-volt">{hl.reason}</span>
                  </div>
                  <span className="text-[10px] font-mono text-white/30">
                    {readableTime(hl.startSeconds)} – {readableTime(hl.endSeconds)}
                  </span>
                </div>
                <p className="text-sm text-white/60 font-dm leading-relaxed italic">"{hl.text}"</p>
                <div className="flex items-center gap-2">
                  {seekable && (
                    <button
                      onClick={() => onSeek!(hl.startSeconds)}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-volt/10 border border-volt/20 text-xs font-mono text-volt hover:bg-volt/20 transition-all"
                    >
                      <Play size={10} /> Jump to moment
                    </button>
                  )}
                  <CopyButton text={hl.text} label="Copy quote" />
                </div>
              </div>
            ))}
          </div>
        )}

        {/* ── Blog ── */}
        {tab === "blog" && (
          <div className="space-y-4">
            {ai.blogPost ? (
              <>
                <div className="max-h-96 overflow-y-auto text-sm text-white/70 font-dm leading-relaxed whitespace-pre-wrap pr-1">
                  {ai.blogPost}
                </div>
                <div className="flex items-center gap-2 pt-2 border-t border-white/[0.06]">
                  <CopyButton text={ai.blogPost} label="Copy blog post" />
                  <span className="text-[10px] font-mono text-white/20">
                    ~{Math.ceil(ai.blogPost.split(" ").length / 200)} min read · {ai.blogPost.split(" ").length} words
                  </span>
                </div>
              </>
            ) : (
              <p className="text-white/30 text-sm py-4 text-center">Blog post not yet generated.</p>
            )}
          </div>
        )}

        {/* ── Thread ── */}
        {tab === "thread" && (
          <div className="space-y-4">
            {ai.tweetThread ? (
              <>
                <div className="space-y-2">
                  {ai.tweetThread.split(/\n(?=\d+\/)/).filter(Boolean).map((tweet, i) => (
                    <div key={i} className="group relative p-4 rounded-xl bg-dark-800 border border-white/[0.06] hover:border-white/10 transition-all">
                      <p className="text-sm text-white/70 font-dm leading-relaxed pr-8">{tweet.trim()}</p>
                      <button
                        onClick={() => navigator.clipboard.writeText(tweet.trim())}
                        className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 transition-opacity p-1 rounded text-white/30 hover:text-white"
                      >
                        <Copy size={12} />
                      </button>
                    </div>
                  ))}
                </div>
                <div className="flex items-center gap-2 pt-2 border-t border-white/[0.06]">
                  <CopyButton text={ai.tweetThread} label="Copy full thread" />
                  <span className="text-[10px] font-mono text-white/20">
                    {ai.tweetThread.split(/\n(?=\d+\/)/).filter(Boolean).length} tweets
                  </span>
                </div>
              </>
            ) : (
              <p className="text-white/30 text-sm py-4 text-center">Thread not yet generated.</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
EOF
echo "✅ frontend/src/components/video/InsightsPanel.tsx  (clickable chapters + highlights)"

# ═════════════════════════════════════════════════════════════════════════════
# 6. SHARE BUTTON
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/ShareButton.tsx" << 'EOF'
"use client";
import { useState } from "react";
import { Share2, CheckCircle, Link2 } from "lucide-react";

export function ShareButton({ videoId }: { videoId: string }) {
  const [copied, setCopied] = useState(false);

  const share = async () => {
    const url = `${window.location.origin}/v/${videoId}`;

    // Use native share sheet on mobile if available
    if (navigator.share) {
      try {
        await navigator.share({ title: "VideoMind", url });
        return;
      } catch { /* user cancelled — fall through to copy */ }
    }

    navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <button
      onClick={share}
      className="flex items-center gap-2 px-3.5 py-2 rounded-xl bg-dark-700 border border-white/10 text-xs font-syne font-semibold text-white/60 hover:text-white hover:border-white/20 transition-all"
    >
      {copied
        ? <><CheckCircle size={12} className="text-volt" /> Link copied</>
        : <><Share2 size={12} /> Share</>}
    </button>
  );
}
EOF
echo "✅ frontend/src/components/video/ShareButton.tsx"

# ═════════════════════════════════════════════════════════════════════════════
# 7. PUBLIC SHARE PAGE  /v/[id]  — no wallet required
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/app/v/[id]/page.tsx" << 'EOF'
"use client";
import { useQuery } from "@tanstack/react-query";
import { getVideo } from "@/lib/api";
import { VideoPlayer, type VideoPlayerHandle } from "@/components/video/VideoPlayer";
import { InsightsPanel } from "@/components/video/InsightsPanel";
import { TranscriptPanel } from "@/components/video/TranscriptPanel";
import { ChatPanel } from "@/components/chat/ChatPanel";
import { ExportMenu } from "@/components/video/ExportMenu";
import { SkeletonVideoPage } from "@/components/ui/SkeletonCard";
import {
  Brain, Zap, AlertTriangle, ExternalLink,
  MessageSquare, X, ArrowRight,
} from "lucide-react";
import Link from "next/link";
import { useRef, useState, useCallback } from "react";
import { clsx } from "clsx";

export default function PublicVideoPage({ params }: { params: { id: string } }) {
  const playerRef = useRef<VideoPlayerHandle>(null);
  const [currentTime, setCurrentTime] = useState(0);
  const [mobileChatOpen, setMobileChatOpen] = useState(false);

  const { data: video, isLoading } = useQuery({
    queryKey: ["public-video", params.id],
    queryFn: () => getVideo(params.id),
    retry: 1,
  });

  const handleSeek = useCallback((seconds: number) => {
    playerRef.current?.seekTo(seconds);
  }, []);

  // ── Loading ────────────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <div className="min-h-screen gradient-mesh">
        <PublicNav />
        <main className="pt-20 pb-16 px-4 sm:px-6 max-w-7xl mx-auto">
          <SkeletonVideoPage />
        </main>
      </div>
    );
  }

  // ── Not found / not ready ──────────────────────────────────────────────
  if (!video || video.status !== "ready") {
    return (
      <div className="min-h-screen gradient-mesh">
        <PublicNav />
        <div className="flex items-center justify-center min-h-[70vh] px-4">
          <div className="text-center space-y-4 max-w-sm">
            <div className="w-14 h-14 rounded-2xl bg-dark-800 border border-white/10 flex items-center justify-center mx-auto">
              <AlertTriangle size={20} className="text-white/20" />
            </div>
            <div>
              <p className="font-syne font-semibold text-white">
                {!video ? "Video not found" : "Video still processing"}
              </p>
              <p className="text-sm text-white/30 font-dm mt-2 leading-relaxed">
                {!video
                  ? "This video may have been deleted or the link is incorrect."
                  : "The AI pipeline is still running. Check back in a few minutes."}
              </p>
            </div>
            <Link href="/" className="inline-flex items-center gap-2 text-volt text-sm font-mono hover:underline">
              Go to VideoMind <ArrowRight size={12} />
            </Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen gradient-mesh">
      <PublicNav />

      <main className="pt-20 pb-24 lg:pb-16 px-4 sm:px-6 max-w-7xl mx-auto">

        {/* Header */}
        <div className="py-5 border-b border-white/[0.06] mb-6">
          <div className="flex items-start justify-between gap-4">
            <div className="flex-1 min-w-0">
              <h1 className="font-syne font-800 text-lg sm:text-2xl text-white leading-tight">
                {video.title}
              </h1>
              {video.description && (
                <p className="text-sm text-white/40 font-dm mt-1.5">{video.description}</p>
              )}
            </div>

            <div className="flex items-center gap-2 shrink-0">
              <ExportMenu
                title={video.title}
                transcript={video.ai?.transcript}
                summary={video.ai?.summary}
                chapters={video.ai?.chapters}
                highlights={video.ai?.highlights}
                tags={video.ai?.tags}
              />
            </div>
          </div>

          {/* Shelby proof */}
          {video.shelby.accountAddress && (
            <a
              href={`https://explorer.shelby.xyz/testnet/accounts/${video.shelby.accountAddress}`}
              target="_blank" rel="noopener noreferrer"
              className="inline-flex items-center gap-2 mt-4 px-3 py-1.5 rounded-full border border-volt/20 bg-volt/5 hover:bg-volt/10 transition-all group"
            >
              <Zap size={11} className="text-volt" />
              <span className="font-mono text-[10px] text-volt/70 group-hover:text-volt">
                Stored on Shelby · {video.shelby.accountAddress.slice(0, 6)}...{video.shelby.accountAddress.slice(-4)}
              </span>
              <ExternalLink size={9} className="text-volt/40" />
            </a>
          )}
        </div>

        {/* Content grid */}
        <div className="grid lg:grid-cols-[1fr_380px] gap-6">
          <div className="space-y-5">
            <VideoPlayer
              ref={playerRef}
              streamUrl={video.streamUrl ?? null}
              title={video.title}
              shelbyAddress={video.shelby.accountAddress}
              blobName={video.shelby.videoBlobName}
              onTimeUpdate={setCurrentTime}
            />

            {video.ai?.tags && video.ai.tags.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {video.ai.tags.map((tag) => (
                  <span key={tag} className="px-3 py-1 rounded-full bg-dark-800 border border-white/[0.06] text-xs font-mono text-white/35">
                    {tag}
                  </span>
                ))}
              </div>
            )}

            <InsightsPanel video={video} onSeek={handleSeek} />

            {video.ai?.transcript && video.ai.transcript.length > 0 && (
              <TranscriptPanel
                transcript={video.ai.transcript}
                currentTime={currentTime}
                onSeek={handleSeek}
              />
            )}
          </div>

          {/* Desktop chat */}
          <div className="hidden lg:block lg:sticky lg:top-20 lg:h-[calc(100vh-5rem)]">
            <div className="glass-card rounded-2xl h-full flex flex-col overflow-hidden">
              <ChatPanel videoId={params.id} videoTitle={video.title} />
            </div>
          </div>
        </div>

        {/* CTA footer */}
        <div className="mt-16 p-6 sm:p-8 glass-card rounded-2xl border border-volt/10 bg-volt/[0.02] text-center space-y-4">
          <div className="w-12 h-12 rounded-2xl bg-volt/10 border border-volt/20 flex items-center justify-center mx-auto">
            <Brain size={20} className="text-volt" />
          </div>
          <div>
            <p className="font-syne font-800 text-white text-xl">
              Turn your videos into AI knowledge bases
            </p>
            <p className="text-white/40 font-dm text-sm mt-2 max-w-md mx-auto leading-relaxed">
              VideoMind transcribes, analyses and makes any video searchable — all stored
              on Shelby Protocol, owned by your wallet.
            </p>
          </div>
          <Link
            href="/"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-volt text-black font-syne font-semibold text-sm hover:bg-volt-dim volt-glow transition-all"
          >
            Try VideoMind free <ArrowRight size={14} />
          </Link>
        </div>
      </main>

      {/* Mobile chat */}
      <button
        onClick={() => setMobileChatOpen(true)}
        className="lg:hidden fixed bottom-6 right-4 z-30 flex items-center gap-2 px-4 py-3 rounded-2xl bg-volt text-black font-syne font-semibold text-sm shadow-lg shadow-volt/20 volt-glow"
      >
        <MessageSquare size={16} /> Ask AI
      </button>

      <div className={clsx(
        "lg:hidden fixed inset-0 z-40 transition-all duration-300",
        mobileChatOpen ? "pointer-events-auto" : "pointer-events-none"
      )}>
        <div
          className={clsx(
            "absolute inset-0 bg-black/70 backdrop-blur-sm transition-opacity duration-300",
            mobileChatOpen ? "opacity-100" : "opacity-0"
          )}
          onClick={() => setMobileChatOpen(false)}
        />
        <div className={clsx(
          "absolute bottom-0 left-0 right-0 glass-card rounded-t-3xl border-t border-white/[0.08] transition-transform duration-300 flex flex-col h-[85vh]",
          mobileChatOpen ? "translate-y-0" : "translate-y-full"
        )}>
          <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06] shrink-0">
            <div className="flex items-center gap-2">
              <Brain size={14} className="text-volt" />
              <span className="text-sm font-syne font-semibold text-white">Ask the Video</span>
            </div>
            <button
              onClick={() => setMobileChatOpen(false)}
              className="w-8 h-8 rounded-lg bg-dark-700 border border-white/10 flex items-center justify-center text-white/40 hover:text-white transition-colors"
            >
              <X size={14} />
            </button>
          </div>
          <div className="flex-1 min-h-0 overflow-hidden">
            <ChatPanel videoId={params.id} videoTitle={video.title} />
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Minimal nav for public pages (no wallet button) ───────────────────────
function PublicNav() {
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 h-16 border-b border-white/[0.06] glass-card">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 h-full flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2 group">
          <div className="relative w-8 h-8">
            <div className="absolute inset-0 rounded-lg bg-volt/20 group-hover:bg-volt/30 transition-colors" />
            <Brain className="relative w-8 h-8 p-1.5 text-volt" strokeWidth={1.5} />
          </div>
          <span className="font-syne font-800 text-lg tracking-tight text-white">
            Video<span className="text-volt">Mind</span>
          </span>
        </Link>

        <div className="flex items-center gap-3">
          <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-full border border-volt/20 bg-volt/5">
            <Zap size={12} className="text-volt" />
            <span className="font-mono text-xs text-volt/80">Shelby Testnet</span>
          </div>
          <Link
            href="/"
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-volt text-black font-syne font-semibold text-xs hover:bg-volt-dim transition-all"
          >
            Try free <ArrowRight size={12} />
          </Link>
        </div>
      </div>
    </nav>
  );
}
EOF
echo "✅ frontend/src/app/v/[id]/page.tsx  (public share page)"

# ═════════════════════════════════════════════════════════════════════════════
# 8. VIDEO DETAIL PAGE — wire everything together
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/app/video/[id]/page.tsx" << 'EOF'
"use client";
import { useQuery } from "@tanstack/react-query";
import { getVideo, setVideoDuration } from "@/lib/api";
import { Navbar } from "@/components/layout/Navbar";
import { ChatPanel } from "@/components/chat/ChatPanel";
import { InsightsPanel } from "@/components/video/InsightsPanel";
import { TranscriptPanel } from "@/components/video/TranscriptPanel";
import { ProcessingStatus } from "@/components/video/ProcessingStatus";
import { VideoPlayer, type VideoPlayerHandle } from "@/components/video/VideoPlayer";
import { RenewButton } from "@/components/video/RenewButton";
import { ExportMenu } from "@/components/video/ExportMenu";
import { ShareButton } from "@/components/video/ShareButton";
import { SkeletonVideoPage } from "@/components/ui/SkeletonCard";
import {
  ArrowLeft, Zap, ExternalLink,
  AlertTriangle, MessageSquare, Brain, X,
} from "lucide-react";
import Link from "next/link";
import { useCallback, useState, useRef } from "react";
import { clsx } from "clsx";

export default function VideoPage({ params }: { params: { id: string } }) {
  const [mobileChatOpen, setMobileChatOpen] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const playerRef = useRef<VideoPlayerHandle>(null);
  const durationSaved = useRef(false);

  const { data: video, isLoading, refetch } = useQuery({
    queryKey: ["video", params.id],
    queryFn: () => getVideo(params.id),
    refetchInterval: (query) =>
      query.state.data?.status && ["ready", "error"].includes(query.state.data.status) ? false : 5000,
    retry: 2,
  });

  const onReady = useCallback(() => { refetch(); }, [refetch]);

  const handleSeek = useCallback((seconds: number) => {
    playerRef.current?.seekTo(seconds);
  }, []);

  // Persist the video duration to Turso once, the first time metadata loads
  const handleDuration = useCallback(async (seconds: number) => {
    if (durationSaved.current) return;
    if (video?.meta?.durationSeconds) return; // already stored
    durationSaved.current = true;
    try {
      await setVideoDuration(params.id, seconds);
      refetch();
    } catch { /* non-critical — ignore */ }
  }, [params.id, video?.meta?.durationSeconds, refetch]);

  if (isLoading) {
    return (
      <div className="min-h-screen gradient-mesh">
        <Navbar />
        <main className="pt-20 sm:pt-24 pb-16 px-4 sm:px-6 max-w-7xl mx-auto">
          <SkeletonVideoPage />
        </main>
      </div>
    );
  }

  if (!video) {
    return (
      <div className="min-h-screen gradient-mesh flex items-center justify-center px-4">
        <div className="text-center space-y-4">
          <div className="w-14 h-14 rounded-2xl bg-dark-800 border border-white/10 flex items-center justify-center mx-auto">
            <AlertTriangle size={20} className="text-white/20" />
          </div>
          <p className="text-white/40 font-dm">Video not found</p>
          <Link href="/" className="text-volt text-sm font-mono hover:underline">← Back to library</Link>
        </div>
      </div>
    );
  }

  const isReady      = video.status === "ready";
  const isError      = video.status === "error";
  const isProcessing = !["ready", "error"].includes(video.status);

  return (
    <div className="min-h-screen gradient-mesh">
      <Navbar />
      <main className="pt-16 sm:pt-20 pb-24 lg:pb-16 px-4 sm:px-6 max-w-7xl mx-auto">

        {/* Header */}
        <div className="py-5 border-b border-white/[0.06] mb-6">
          <div className="flex items-start gap-3">
            <Link
              href="/"
              className="flex items-center gap-1.5 text-white/30 hover:text-white text-xs font-mono transition-colors mt-1 shrink-0"
            >
              <ArrowLeft size={12} /> Library
            </Link>

            <div className="flex-1 min-w-0">
              <h1 className="font-syne font-800 text-lg sm:text-xl text-white leading-tight line-clamp-2">
                {video.title}
              </h1>
              {video.description && (
                <p className="text-sm text-white/40 font-dm mt-1 line-clamp-1">{video.description}</p>
              )}
            </div>

            {video.shelby.accountAddress && (
              <a
                href={`https://explorer.shelby.xyz/testnet/accounts/${video.shelby.accountAddress}`}
                target="_blank" rel="noopener noreferrer"
                className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-xl border border-volt/20 bg-volt/5 hover:bg-volt/10 transition-all group shrink-0"
              >
                <Zap size={11} className="text-volt" />
                <span className="font-mono text-[10px] text-volt/70 group-hover:text-volt hidden sm:block">
                  {video.shelby.accountAddress.slice(0, 6)}...{video.shelby.accountAddress.slice(-4)}
                </span>
                <ExternalLink size={10} className="text-volt/40" />
              </a>
            )}
          </div>

          {/* Action row — share, export */}
          {isReady && (
            <div className="flex items-center gap-2 mt-4 flex-wrap">
              <ShareButton videoId={params.id} />
              <ExportMenu
                title={video.title}
                transcript={video.ai?.transcript}
                summary={video.ai?.summary}
                chapters={video.ai?.chapters}
                highlights={video.ai?.highlights}
                tags={video.ai?.tags}
              />
              {video.streamUrl && (
                <div className="ml-auto">
                  <RenewButton
                    streamUrl={video.streamUrl}
                    videoBlobName={video.shelby.videoBlobName}
                    onRenewed={() => refetch()}
                  />
                </div>
              )}
            </div>
          )}
        </div>

        {/* Processing */}
        {isProcessing && (
          <div className="max-w-lg mx-auto py-8">
            <ProcessingStatus videoId={params.id} onReady={onReady} />
          </div>
        )}

        {/* Error */}
        {isError && (
          <div className="max-w-lg mx-auto py-8">
            <div className="glass-card rounded-2xl p-8 text-center space-y-4">
              <AlertTriangle size={32} className="text-red-400 mx-auto" />
              <div>
                <p className="font-syne font-semibold text-white">Processing failed</p>
                <p className="text-sm text-white/40 font-dm mt-1">
                  Something went wrong during AI processing.
                </p>
              </div>
              <Link
                href="/upload"
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-volt text-black font-syne font-semibold text-sm hover:bg-volt-dim transition-all"
              >
                Try uploading again
              </Link>
            </div>
          </div>
        )}

        {/* Ready */}
        {isReady && (
          <div className="grid lg:grid-cols-[1fr_380px] gap-6">
            <div className="space-y-5">
              <VideoPlayer
                ref={playerRef}
                streamUrl={video.streamUrl ?? null}
                title={video.title}
                shelbyAddress={video.shelby.accountAddress}
                blobName={video.shelby.videoBlobName}
                onDuration={handleDuration}
                onTimeUpdate={setCurrentTime}
              />

              {video.ai?.tags && video.ai.tags.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {video.ai.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 rounded-full bg-dark-800 border border-white/[0.06] text-xs font-mono text-white/35"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              )}

              {/* Clickable chapters + highlights */}
              <InsightsPanel video={video} onSeek={handleSeek} />

              {/* Clickable transcript with search + auto-scroll */}
              {video.ai?.transcript && video.ai.transcript.length > 0 && (
                <TranscriptPanel
                  transcript={video.ai.transcript}
                  currentTime={currentTime}
                  onSeek={handleSeek}
                />
              )}
            </div>

            <div className="hidden lg:block lg:sticky lg:top-20 lg:h-[calc(100vh-5rem)]">
              <div className="glass-card rounded-2xl h-full flex flex-col overflow-hidden">
                <ChatPanel videoId={params.id} videoTitle={video.title} />
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Mobile chat */}
      {isReady && (
        <>
          <button
            onClick={() => setMobileChatOpen(true)}
            className="lg:hidden fixed bottom-6 right-4 z-30 flex items-center gap-2 px-4 py-3 rounded-2xl bg-volt text-black font-syne font-semibold text-sm shadow-lg shadow-volt/20 volt-glow"
          >
            <MessageSquare size={16} /> Ask AI
          </button>

          <div className={clsx(
            "lg:hidden fixed inset-0 z-40 transition-all duration-300",
            mobileChatOpen ? "pointer-events-auto" : "pointer-events-none"
          )}>
            <div
              className={clsx(
                "absolute inset-0 bg-black/70 backdrop-blur-sm transition-opacity duration-300",
                mobileChatOpen ? "opacity-100" : "opacity-0"
              )}
              onClick={() => setMobileChatOpen(false)}
            />
            <div className={clsx(
              "absolute bottom-0 left-0 right-0 glass-card rounded-t-3xl border-t border-white/[0.08] transition-transform duration-300 flex flex-col h-[85vh]",
              mobileChatOpen ? "translate-y-0" : "translate-y-full"
            )}>
              <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06] shrink-0">
                <div className="flex items-center gap-2">
                  <Brain size={14} className="text-volt" />
                  <span className="text-sm font-syne font-semibold text-white">Ask the Video</span>
                </div>
                <button
                  onClick={() => setMobileChatOpen(false)}
                  className="w-8 h-8 rounded-lg bg-dark-700 border border-white/10 flex items-center justify-center text-white/40 hover:text-white transition-colors"
                >
                  <X size={14} />
                </button>
              </div>
              <div className="flex-1 min-h-0 overflow-hidden">
                <ChatPanel videoId={params.id} videoTitle={video.title} />
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
EOF
echo "✅ frontend/src/app/video/[id]/page.tsx  (seek + export + share + duration)"

# ═════════════════════════════════════════════════════════════════════════════
# 9. VIDEO CARD — show duration
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/components/video/VideoCard.tsx" << 'EOF'
"use client";
import Link from "next/link";
import {
  Film, Clock, CheckCircle, Loader2, AlertTriangle,
  Zap, RefreshCw, Trash2, X, Play,
} from "lucide-react";
import { clsx } from "clsx";
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useWallet } from "@aptos-labs/wallet-adapter-react";
import { api } from "@/lib/api";
import type { VideoRecord } from "@/lib/api";

const STATUS_CONFIG = {
  uploading:    { label: "Uploading",    spin: true },
  processing:   { label: "Processing",   spin: true },
  transcribing: { label: "Transcribing", spin: true },
  analyzing:    { label: "Analyzing",    spin: true },
  ready:        { label: "Ready",        spin: false },
  error:        { label: "Failed",       spin: false },
};

function formatDate(ms: number) {
  return new Intl.DateTimeFormat("en", {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  }).format(new Date(ms));
}

function formatBytes(bytes: number) {
  if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(0)} KB`;
  if (bytes < 1024 ** 3) return `${(bytes / 1024 ** 2).toFixed(1)} MB`;
  return `${(bytes / 1024 ** 3).toFixed(2)} GB`;
}

/** 1:23:45 or 4:32 */
function formatDuration(sec?: number) {
  if (!sec || !isFinite(sec)) return null;
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export function VideoCard({ video }: { video: VideoRecord }) {
  const cfg = STATUS_CONFIG[video.status];
  const isError = video.status === "error";
  const isProcessing = !["ready", "error"].includes(video.status);
  const duration = formatDuration(video.meta.durationSeconds);

  const { account } = useWallet();
  const queryClient = useQueryClient();
  const walletAddress = account?.address?.toString();

  const [confirm, setConfirm] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [deleted, setDeleted] = useState(false);

  const handleDelete = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (!confirm) { setConfirm(true); return; }

    setDeleting(true);
    try {
      await api.delete(`/api/videos/${video.id}`);
      setDeleted(true);
      queryClient.invalidateQueries({ queryKey: ["videos", walletAddress] });
      queryClient.invalidateQueries({ queryKey: ["shelby-stats", walletAddress] });
      queryClient.invalidateQueries({ queryKey: ["shelby-badge", walletAddress] });
    } catch {
      setDeleting(false);
      setConfirm(false);
    }
  };

  const cancelDelete = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setConfirm(false);
  };

  if (deleted) return null;

  return (
    <div className="relative group">
      <Link href={`/video/${video.id}`} className="block">
        <div className={clsx(
          "glass-card-hover rounded-2xl overflow-hidden transition-all duration-300",
          isError && "border border-red-500/20 hover:border-red-500/30",
          confirm && "ring-2 ring-red-500/40"
        )}>
          {/* Thumbnail */}
          <div className="relative aspect-video bg-dark-800 overflow-hidden">
            <div
              className="absolute inset-0 opacity-[0.03]"
              style={{
                backgroundImage:
                  "linear-gradient(rgba(200,255,0,0.5) 1px, transparent 1px), linear-gradient(90deg, rgba(200,255,0,0.5) 1px, transparent 1px)",
                backgroundSize: "40px 40px",
              }}
            />

            <div className="absolute inset-0 flex items-center justify-center">
              {isError
                ? <AlertTriangle size={32} className="text-red-400/20" strokeWidth={1} />
                : <Film size={40} className="text-white/10" strokeWidth={1} />}
            </div>

            {isProcessing && <div className="absolute inset-0 shimmer opacity-30" />}

            {/* Play overlay on hover */}
            {video.status === "ready" && (
              <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                <div className="w-12 h-12 rounded-full bg-volt/20 border border-volt/40 backdrop-blur-sm flex items-center justify-center">
                  <Play size={18} className="text-volt ml-0.5" />
                </div>
              </div>
            )}

            {/* Status badge */}
            <div className={clsx(
              "absolute top-3 right-3 flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-mono border",
              video.status === "ready"
                ? "bg-volt/10 border-volt/20 text-volt"
                : isError
                ? "bg-red-500/10 border-red-500/20 text-red-400"
                : "bg-dark-900/80 border-white/10 text-white/60"
            )}>
              {cfg.spin
                ? <Loader2 size={10} className="animate-spin" />
                : isError
                ? <AlertTriangle size={10} />
                : <CheckCircle size={10} />}
              {cfg.label}
            </div>

            {/* Delete button */}
            {!confirm && (
              <button
                onClick={handleDelete}
                className="absolute top-3 left-3 w-7 h-7 rounded-lg bg-dark-900/80 border border-white/10 flex items-center justify-center text-white/30 hover:text-red-400 hover:border-red-500/30 hover:bg-red-500/10 transition-all opacity-0 group-hover:opacity-100"
                title="Delete video"
              >
                <Trash2 size={12} />
              </button>
            )}

            {/* Duration badge */}
            {duration && (
              <div className="absolute bottom-3 right-3 px-2 py-0.5 rounded bg-black/70 border border-white/10">
                <span className="font-mono text-[10px] text-white/70 tabular-nums">{duration}</span>
              </div>
            )}

            {/* Shelby badge */}
            <div className="absolute bottom-3 left-3 flex items-center gap-1 px-2 py-1 rounded bg-dark-900/70 border border-white/10">
              <Zap size={10} className="text-volt" />
              <span className="font-mono text-[10px] text-white/40">Shelby</span>
            </div>
          </div>

          {/* Content */}
          <div className="p-4 space-y-3">
            <h3 className={clsx(
              "font-syne font-semibold text-sm leading-snug line-clamp-2 transition-colors",
              isError ? "text-white/50 group-hover:text-white/70" : "text-white group-hover:text-volt"
            )}>
              {video.title}
            </h3>

            {isError && (
              <div className="flex items-center gap-1.5 text-[11px] font-mono text-red-400/60">
                <RefreshCw size={9} /> Click to view details or retry
              </div>
            )}

            {!isError && video.ai?.tags && video.ai.tags.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {video.ai.tags.slice(0, 3).map((tag) => (
                  <span
                    key={tag}
                    className="px-2 py-0.5 rounded text-[10px] font-mono bg-dark-700 text-white/40 border border-white/[0.06]"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            )}

            <div className="flex items-center justify-between pt-1 border-t border-white/[0.06]">
              <div className="flex items-center gap-1 text-[11px] text-white/30 font-mono">
                <Clock size={10} />
                {formatDate(video.createdAt)}
              </div>
              <span className="text-[11px] text-white/20 font-mono">
                {formatBytes(video.meta.sizeBytes)}
              </span>
            </div>
          </div>
        </div>
      </Link>

      {/* Delete confirm */}
      {confirm && (
        <div
          className="absolute inset-0 rounded-2xl bg-dark-950/90 backdrop-blur-sm flex flex-col items-center justify-center gap-4 p-5 z-10"
          onClick={(e) => e.preventDefault()}
        >
          <div className="w-10 h-10 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center justify-center">
            <Trash2 size={16} className="text-red-400" />
          </div>
          <div className="text-center">
            <p className="font-syne font-semibold text-white text-sm">Delete this video?</p>
            <p className="text-[11px] text-white/35 font-dm mt-1 leading-relaxed">
              Removed from your library. The Shelby blob expires naturally.
            </p>
          </div>
          <div className="flex items-center gap-2 w-full">
            <button
              onClick={handleDelete}
              disabled={deleting}
              className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-xl bg-red-500/20 border border-red-500/30 text-red-400 text-xs font-syne font-semibold hover:bg-red-500/30 transition-all disabled:opacity-50"
            >
              {deleting ? <Loader2 size={11} className="animate-spin" /> : <Trash2 size={11} />}
              {deleting ? "Deleting..." : "Delete"}
            </button>
            <button
              onClick={cancelDelete}
              className="flex-1 flex items-center justify-center gap-1.5 py-2 rounded-xl bg-dark-700 border border-white/10 text-white/50 text-xs font-syne font-semibold hover:border-white/20 transition-all"
            >
              <X size={11} /> Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
EOF
echo "✅ frontend/src/components/video/VideoCard.tsx  (duration badge + play overlay)"

# ═════════════════════════════════════════════════════════════════════════════
# 10. API CLIENT — add setVideoDuration
# ═════════════════════════════════════════════════════════════════════════════
cat > "$FE/src/lib/api.ts" << 'EOF'
import axios, { type AxiosError } from "axios";

const BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000";

export const api = axios.create({ baseURL: BASE, timeout: 120_000 });

api.interceptors.response.use(
  (res) => res,
  (err: AxiosError<{ error?: string }>) => {
    const serverMsg = err.response?.data?.error;
    const statusCode = err.response?.status;
    let message: string;
    if (serverMsg) message = serverMsg;
    else if (err.code === "ECONNABORTED" || err.message.includes("timeout"))
      message = "Request timed out. The server may be busy — please try again.";
    else if (!err.response)
      message = "Cannot reach the VideoMind server. Is the backend running?";
    else if (statusCode === 413) message = "File is too large. Maximum size is 2 GB.";
    else if (statusCode === 415) message = "Unsupported file type. Please upload MP4, WebM, MOV, AVI, or MKV.";
    else if (statusCode === 500) message = "Server error. Check the backend logs for details.";
    else message = err.message ?? "An unexpected error occurred.";
    return Promise.reject(new Error(message));
  }
);

// ── Upload flow ─────────────────────────────────────────────────────────────
export async function prepareVideo(
  file: File, title: string, description: string,
  onProgress?: (pct: number) => void
): Promise<{ id: string; videoBlobName: string; base64Data: string; mimeType: string }> {
  const form = new FormData();
  form.append("video", file);
  form.append("title", title);
  form.append("description", description);
  const res = await api.post("/api/videos/prepare", form, {
    headers: { "Content-Type": "multipart/form-data" },
    onUploadProgress: (e) => { if (e.total) onProgress?.(Math.round((e.loaded / e.total) * 100)); },
  });
  return res.data;
}

export async function confirmVideo(payload: {
  id: string; accountAddress: string; txHash: string; videoBlobName: string;
}): Promise<{ id: string; status: string }> {
  const res = await api.post("/api/videos/confirm", payload);
  return res.data;
}

// ── Video queries ───────────────────────────────────────────────────────────
export async function getVideos(walletAddress?: string): Promise<VideoRecord[]> {
  if (!walletAddress) return [];
  const res = await api.get("/api/videos", { params: { wallet: walletAddress } });
  return res.data.videos as VideoRecord[];
}

export async function getVideo(id: string) {
  const res = await api.get(`/api/videos/${id}`);
  return res.data as VideoRecord & { streamUrl: string | null };
}

export async function getVideoStatus(id: string) {
  const res = await api.get(`/api/videos/${id}/status`);
  return res.data as { id: string; status: string };
}

/** Persist the video duration once it's known from the player. */
export async function setVideoDuration(id: string, seconds: number) {
  const res = await api.patch(`/api/videos/${id}/duration`, { durationSeconds: seconds });
  return res.data as { success: boolean };
}

// ── AI ──────────────────────────────────────────────────────────────────────
export async function chatWithVideo(videoId: string, question: string) {
  const res = await api.post(`/api/chat/${videoId}`, { question });
  return res.data as { answer: string; sources: Array<{ time: number; text: string }> };
}

export async function searchAllVideos(query: string, walletAddress?: string) {
  const res = await api.post("/api/chat/search/all", { query, wallet: walletAddress });
  return res.data as {
    results: Array<{
      videoId: string; title: string;
      matches: Array<{ time: number; text: string }>;
    }>;
  };
}

export async function deleteAllVideos(walletAddress: string) {
  const res = await api.delete("/api/videos/all", { params: { wallet: walletAddress } });
  return res.data as { success: boolean; deleted: number; message: string };
}

// ── Types ───────────────────────────────────────────────────────────────────
export interface VideoRecord {
  id: string;
  title: string;
  description?: string;
  createdAt: number;
  status: "uploading" | "processing" | "transcribing" | "analyzing" | "ready" | "error";
  shelby: {
    videoBlobName: string;
    accountAddress: string;
    videoTxHash: string;
    transcriptBlobName?: string;
    metaBlobName?: string;
    expiresAt?: number;
  };
  ai?: {
    transcript?: Array<{ start: number; end: number; text: string }>;
    summary?: string;
    chapters?: Array<{ title: string; startSeconds: number; summary: string }>;
    highlights?: Array<{ startSeconds: number; endSeconds: number; reason: string; text: string }>;
    tags?: string[];
    blogPost?: string;
    tweetThread?: string;
  };
  meta: { sizeBytes: number; mimeType: string; durationSeconds?: number };
  streamUrl?: string | null;
}
EOF
echo "✅ frontend/src/lib/api.ts  (setVideoDuration added)"

# ═════════════════════════════════════════════════════════════════════════════
# 11. BACKEND — PATCH /api/videos/:id/duration
# ═════════════════════════════════════════════════════════════════════════════
python3 - << 'PYEOF'
import re, sys, os

path = "backend/src/routes/videos.ts"
with open(path) as f:
    src = f.read()

# Skip if already patched
if "/:id/duration" in src:
    print("   (duration route already present — skipping)")
    sys.exit(0)

route = '''
// ── PATCH /api/videos/:id/duration ───────────────────────────────────────────
// Called once by the frontend player when video metadata loads.
router.patch("/:id/duration", async (req, res) => {
  try {
    const { durationSeconds } = req.body as { durationSeconds: number };
    if (typeof durationSeconds !== "number" || !isFinite(durationSeconds) || durationSeconds <= 0) {
      return res.status(400).json({ error: "durationSeconds must be a positive number" });
    }

    const video = await store.get(req.params.id);
    if (!video) return res.status(404).json({ error: "Video not found" });

    await store.update(req.params.id, {
      meta: { ...video.meta, durationSeconds },
    });

    return res.json({ success: true });
  } catch (err: any) {
    return res.status(500).json({ error: err.message });
  }
});

// ── DELETE /api/videos/all'''

# Insert before the DELETE /all route
src = src.replace("\n// ── DELETE /api/videos/all", route, 1)

with open(path, "w") as f:
    f.write(src)
print("   patched backend/src/routes/videos.ts")
PYEOF
echo "✅ backend/src/routes/videos.ts  (PATCH /:id/duration)"

# ─────────────────────────────────────────────────────────────────────────────
echo ""
echo "════════════════════════════════════════════════════"
echo "✅ BATCH 1 COMPLETE"
echo "════════════════════════════════════════════════════"
echo ""
echo "  1. Click-to-seek     — transcript, chapters & highlights"
echo "  2. Transcript search — inline search + auto-scroll toggle"
echo "  3. Exports           — .srt / .vtt / .md / .txt"
echo "  4. Video duration    — captured from player, stored in Turso"
echo "  5. Public share      — /v/{id}, no wallet required"
echo ""
echo "Next:"
echo "  git add ."
echo "  git commit -m 'feat: batch 1 — seek, search, exports, duration, share links'"
echo "  git push"
