#!/usr/bin/env bash
# ============================================================================
# VideoMind rebuild, Part 3c step 1: can this server run FFmpeg?
# ============================================================================
# FOR THE rebuild BRANCH ONLY. It refuses to run on main.
#
# Transcoding (HLS streams and thumbnails) needs FFmpeg, and where it
# can run decides how Part 3c is built. Render's documentation lists
# FFmpeg as installed, but not which version, and it says nothing about
# how fast it is on the instance this service runs on. This part
# measures instead of guessing. It changes nothing a user can see.
#
# After this part there is one new address on the backend:
#
#   /api/health/media          what the server is (CPU, memory, disk)
#                              and the result of the last run
#   /api/health/media?run=1    start a run, at most one every 10 minutes
#
# A run makes its own 20 second test video (no user file is touched)
# and does what transcoding would do, smallest first: one picture, a
# 360p stream, a 720p + 360p ladder, a 1080p stream. It reports the
# time, the speed and the memory of each. Every step is recorded before
# it starts, so if the server is stopped for using too much memory, the
# report shows which step did it.
#
#   BACKEND   1 new file, 1 changed (index.ts mounts the route).
#             One small table, media_probe_steps, is created on first
#             use. No new packages.
#   FRONTEND  no changes.
#
#   ./vm_media_probe.sh            apply (needs Part 3b on the branch)
#   ./vm_media_probe.sh --force    apply even if local files differ from GitHub
#   ./vm_media_probe.sh --revert   restore everything from the latest backup
#
# Run from the repo root (dir containing backend/ and frontend/).
# ============================================================================
set -euo pipefail

MARKER="vm_media_probe"
STAMP="$(date +%Y%m%d-%H%M%S)"
BAKDIR=".vm_media_probe_backups"

ADD=(
  "backend/src/routes/mediaProbe.ts"
)
MOD=(
  "backend/src/index.ts"
)
PRE_MOD=(
  "194084419776d7d7cc80ac119ca5b504f144f6e8848b1cfa4348135d6637398b"
)
NEW_MOD=(
  "8159fa56f0c86a8772f71c2e7a1d9508a73604d0c7a447bf499386dcc4368a46"
)
NEW_ADD=(
  "157032c092e603a064b3928f50dfea17c98ebeed1df3c9d411d178cadf172afe"
)

say() { printf '  %s\n' "$1"; }
die() { printf 'ERROR: %s\n' "$1" >&2; exit 1; }
sha() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
  else shasum -a 256 "$1" | cut -d' ' -f1; fi
}
bname() { printf '%s' "$1" | sed 's#/#__#g'; }

[ -d frontend ] && [ -d backend ] || die "Run from repo root (dir with backend/ and frontend/)."

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ "$BRANCH" = "main" ]; then
  die "You are on main. This part is for the rebuild branch. Run: git checkout rebuild"
fi

restore_from() {
  local f
  for f in "${MOD[@]}"; do
    if [ -f "$1/$(bname "$f")" ]; then mkdir -p "$(dirname "$f")"; cp "$1/$(bname "$f")" "$f"; fi
  done
  for f in "${ADD[@]}"; do
    if [ -f "$1/$(bname "$f")" ]; then cp "$1/$(bname "$f")" "$f"; else rm -f "$f"; fi
  done
}

if [ "${1:-}" = "--revert" ]; then
  [ -d "$BAKDIR" ] || die "No backup dir. Nothing to revert."
  LATEST="$(ls -1d "$BAKDIR"/*/ 2>/dev/null | sort | tail -1)"
  [ -n "$LATEST" ] || die "No backups found."
  restore_from "${LATEST%/}"
  say "Restored 1 changed file and removed 1 new file, from $LATEST"
  exit 0
fi

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f "${ADD[0]}" ] && grep -q "$MARKER" "${ADD[0]}" && grep -q "$MARKER" "backend/src/index.ts"; then
  say "Already applied ($MARKER marker present). Use --revert to undo."
  exit 0
fi

grep -q "vm_info" backend/src/lib/videoInfo.ts 2>/dev/null || die "Part 3b is not on this branch. Run: git pull origin rebuild"

# ---- pre image check: every file must match what this part was built on ----
check_pre() {
  [ -f "$1" ] || die "$1 not found. Nothing changed."
  if [ "$(sha "$1")" != "$2" ]; then
    if [ "$FORCE" = "1" ]; then say "WARNING: $1 differs from GitHub rebuild (25bd1cd). Proceeding (--force)."
    else die "$1 differs from the GitHub rebuild version this part was built on (25bd1cd). Nothing changed. Run git pull origin rebuild, push or stash local edits, or run again with --force."; fi
  fi
}
i=0; for f in "${MOD[@]}"; do check_pre "$f" "${PRE_MOD[$i]}"; i=$((i+1)); done
for f in "${ADD[@]}"; do
  if [ -f "$f" ] && [ "$FORCE" != "1" ]; then die "$f already exists but is not this part's version. Nothing changed. Run again with --force to overwrite it."; fi
done

# ---- decode + verify every payload BEFORE touching anything ----
TMPD="$(mktemp -d)"
trap 'rm -rf "$TMPD"' EXIT
verify() {
  [ -s "$1" ] || die "$3: base64 decode produced an empty file. Nothing written."
  [ "$(sha "$1")" = "$2" ] || die "$3: payload checksum mismatch (script was corrupted in transit). Nothing written."
}

base64 -d > "$TMPD/m0" <<'B64_M0' || die "backend/src/index.ts: base64 decode failed."
aW1wb3J0ICJkb3RlbnYvY29uZmlnIjsKaW1wb3J0IGV4cHJlc3MgZnJvbSAiZXhwcmVzcyI7Cmlt
cG9ydCBjb3JzIGZyb20gImNvcnMiOwppbXBvcnQgeyBtaWdyYXRlIH0gZnJvbSAiLi9saWIvZGIu
anMiOwppbXBvcnQgdmlkZW9zUm91dGVyIGZyb20gIi4vcm91dGVzL3ZpZGVvcy5qcyI7CmltcG9y
dCBjaGF0Um91dGVyIGZyb20gIi4vcm91dGVzL2NoYXQuanMiOwppbXBvcnQgc3RhdHNSb3V0ZXIg
ZnJvbSAiLi9yb3V0ZXMvc3RhdHMuanMiOwppbXBvcnQgbGVhcm5Sb3V0ZXIgZnJvbSAiLi9yb3V0
ZXMvbGVhcm4uanMiOwppbXBvcnQgYXV0aFJvdXRlciBmcm9tICIuL3JvdXRlcy9hdXRoLmpzIjsK
Ly8gdm1fam9iczogZHVyYWJsZSBwcm9jZXNzaW5nIGpvYnMKaW1wb3J0IHsgc3RhcnRSdW5uZXIs
IHR5cGUgUnVubmVyIH0gZnJvbSAiLi9saWIvcnVubmVyLmpzIjsKaW1wb3J0IHsgcmVnaXN0ZXJQ
aXBlbGluZSB9IGZyb20gIi4vc2VydmljZXMvcGlwZWxpbmUuanMiOwovLyB2bV9zdG9yYWdlOiBm
aWxlIHN0b3JhZ2UgYW5kIHRoZSB1c2FnZSBsZWRnZXIKaW1wb3J0IHVzYWdlUm91dGVyIGZyb20g
Ii4vcm91dGVzL3VzYWdlLmpzIjsKLy8gdm1fdXBsb2FkOiByZXN1bWFibGUgdXBsb2FkcyBzdHJh
aWdodCB0byBzdG9yYWdlCmltcG9ydCB1cGxvYWRzUm91dGVyIGZyb20gIi4vcm91dGVzL3VwbG9h
ZHMuanMiOwppbXBvcnQgeyBjaGVja1N0b3JhZ2UsIHN0b3JhZ2VIZWFsdGggfSBmcm9tICIuL2xp
Yi9zdG9yYWdlLmpzIjsKaW1wb3J0IHsgc3RhcnRIb3VzZWtlZXBpbmcgfSBmcm9tICIuL2xpYi9h
c3NldHMuanMiOwovLyB2bV9pbmZvOiBjb2xsZWN0aW9ucyBvZiB2aWRlb3MKaW1wb3J0IGNvbGxl
Y3Rpb25zUm91dGVyIGZyb20gIi4vcm91dGVzL2NvbGxlY3Rpb25zLmpzIjsKLy8gdm1fbWVkaWFf
cHJvYmU6IG1lYXN1cmVzIHdoZXRoZXIgdGhpcyBzZXJ2ZXIgY2FuIHJ1biBGRm1wZWcsIGJlZm9y
ZSB0cmFuc2NvZGluZyBpcyBidWlsdAppbXBvcnQgbWVkaWFQcm9iZVJvdXRlciBmcm9tICIuL3Jv
dXRlcy9tZWRpYVByb2JlLmpzIjsKCmNvbnN0IGFwcCA9IGV4cHJlc3MoKTsKY29uc3QgUE9SVCA9
IHByb2Nlc3MuZW52LlBPUlQgPz8gNDAwMDsKCmNvbnN0IGFsbG93ZWRPcmlnaW5zID0gKHByb2Nl
c3MuZW52LkZST05URU5EX1VSTCA/PyAiaHR0cDovL2xvY2FsaG9zdDozMDAwIikKICAuc3BsaXQo
IiwiKS5tYXAoKHMpID0+IHMudHJpbSgpKS5maWx0ZXIoQm9vbGVhbik7CgphcHAudXNlKGNvcnMo
ewogIG9yaWdpbjogKG9yaWdpbiwgY2FsbGJhY2spID0+IHsKICAgIGlmICghb3JpZ2luKSByZXR1
cm4gY2FsbGJhY2sobnVsbCwgdHJ1ZSk7CiAgICBpZiAoYWxsb3dlZE9yaWdpbnMuaW5jbHVkZXMo
b3JpZ2luKSkgcmV0dXJuIGNhbGxiYWNrKG51bGwsIHRydWUpOwogICAgY2FsbGJhY2sobmV3IEVy
cm9yKGBDT1JTOiAke29yaWdpbn0gbm90IGFsbG93ZWRgKSk7CiAgfSwKICBjcmVkZW50aWFsczog
dHJ1ZSwKfSkpOwoKYXBwLnVzZShleHByZXNzLmpzb24oeyBsaW1pdDogIjEwbWIiIH0pKTsKYXBw
LnVzZShleHByZXNzLnVybGVuY29kZWQoeyBleHRlbmRlZDogdHJ1ZSB9KSk7CgovLyB2bV9zaWdu
aW46IHdhbGxldCBzaWduIGluIGFuZCBzZXNzaW9ucwphcHAudXNlKCIvYXBpL2F1dGgiLCBhdXRo
Um91dGVyKTsKYXBwLnVzZSgiL2FwaS91cGxvYWRzIiwgdXBsb2Fkc1JvdXRlcik7CmFwcC51c2Uo
Ii9hcGkvdmlkZW9zIiwgdmlkZW9zUm91dGVyKTsKYXBwLnVzZSgiL2FwaS9jaGF0IiwgY2hhdFJv
dXRlcik7CmFwcC51c2UoIi9hcGkvc2hlbGJ5Iiwgc3RhdHNSb3V0ZXIpOwphcHAudXNlKCIvYXBp
L2xlYXJuIiwgbGVhcm5Sb3V0ZXIpOwphcHAudXNlKCIvYXBpL3VzYWdlIiwgdXNhZ2VSb3V0ZXIp
OwphcHAudXNlKCIvYXBpL2NvbGxlY3Rpb25zIiwgY29sbGVjdGlvbnNSb3V0ZXIpOwphcHAudXNl
KCIvYXBpL2hlYWx0aC9tZWRpYSIsIG1lZGlhUHJvYmVSb3V0ZXIpOwoKYXBwLmdldCgiL2FwaS9o
ZWFsdGgiLCAoX3JlcSwgcmVzKSA9PiB7CiAgY29uc3QgcyA9IHN0b3JhZ2VIZWFsdGgoKTsKICBy
ZXMuanNvbih7CiAgICBzdGF0dXM6ICJvayIsIHNlcnZpY2U6ICJWaWRlb01pbmQgQVBJIiwgdGlt
ZXN0YW1wOiBuZXcgRGF0ZSgpLnRvSVNPU3RyaW5nKCksCiAgICAvLyB2bV9zdG9yYWdlOiB3aGlj
aCBzdG9yYWdlIGlzIGluIHVzZSBhbmQgd2hldGhlciBpdHMgc3RhcnR1cCBjaGVjayBwYXNzZWQK
ICAgIHN0b3JhZ2U6IHsgZHJpdmVyOiBzLmRyaXZlciwgZHVyYWJsZTogcy5kdXJhYmxlLCBvazog
cy5vayB9LAogIH0pOwp9KTsKCi8vIHZtX3NoZWxieTA5ZDogdGhlIDYtaG91cmx5IGJsb2IgcmVu
ZXdhbCBjcm9uIGlzIGdvbmUuIFNoZWxieSBzdG9yYWdlIGlzCi8vIHByZXBhaWQgaW4gcGF5bWVu
dCBlcG9jaHMgYXQgcmVnaXN0cmF0aW9uIGFuZCB0aGUgY29udHJhY3QgaGFzIG5vIHJlbmV3IGNh
bGwuCgphc3luYyBmdW5jdGlvbiBtYWluKCkgewogIGF3YWl0IG1pZ3JhdGUoKTsKCiAgLy8gdm1f
c3RvcmFnZTogcHJvdmUgc3RvcmFnZSB3b3JrcyBiZWZvcmUgdGFraW5nIHVwbG9hZHMuIFdyb25n
IG9yCiAgLy8gbWlzc2luZyBzZXR0aW5ncyBzdG9wIHRoZSBzdGFydCB3aXRoIGEgY2xlYXIgbWVz
c2FnZS4gQSBzdG9yYWdlIHRoYXQKICAvLyBjYW5ub3QgYmUgcmVhY2hlZCBpcyBsb2dnZWQgYW5k
IHRoZSBzZXJ2ZXIgc3RpbGwgc3RhcnRzLgogIGF3YWl0IGNoZWNrU3RvcmFnZSgpOwoKICAvLyB2
bV9qb2JzOiB0aGUgam9iIHJ1bm5lciBsaXZlcyBpbiB0aGlzIHNlcnZpY2UgYnkgZGVmYXVsdC4K
ICAvLyBKT0JTX1JVTk5FUj1vZmYgdHVybnMgaXQgb2ZmIGhlcmUgKHNlZSBzcmMvd29ya2VyLnRz
KS4KICBsZXQgcnVubmVyOiBSdW5uZXIgfCBudWxsID0gbnVsbDsKICBpZiAocHJvY2Vzcy5lbnYu
Sk9CU19SVU5ORVIgIT09ICJvZmYiKSB7CiAgICByZWdpc3RlclBpcGVsaW5lKCk7CiAgICBydW5u
ZXIgPSBzdGFydFJ1bm5lcigpOwogICAgc3RhcnRIb3VzZWtlZXBpbmcoKTsKICB9CiAgLy8gT24g
YSBkZXBsb3kgdGhlIHBsYXRmb3JtIHNlbmRzIFNJR1RFUk0uIEhhbmQgcnVubmluZyBqb2JzIGJh
Y2sgc28gdGhlCiAgLy8gbmV4dCBpbnN0YW5jZSByZXN1bWVzIHRoZW0gYXQgb25jZS4KICBjb25z
dCBzaHV0ZG93biA9IGFzeW5jICgpID0+IHsKICAgIGlmIChydW5uZXIpIGF3YWl0IHJ1bm5lci5z
dG9wKCkuY2F0Y2goKCkgPT4ge30pOwogICAgcHJvY2Vzcy5leGl0KDApOwogIH07CiAgcHJvY2Vz
cy5vbigiU0lHVEVSTSIsIHNodXRkb3duKTsKICBwcm9jZXNzLm9uKCJTSUdJTlQiLCBzaHV0ZG93
bik7CgogIGFwcC5saXN0ZW4oUE9SVCwgKCkgPT4gewogICAgY29uc29sZS5sb2coYArilZTilZDi
lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi
lZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDilZDi
lZDilZDilZDilZcK4pWRICAgICAgIFZpZGVvTWluZCBBUEkgU2VydmVyICAgICAgICAgICAgICAg
4pWRCuKVkSAgICAgICBSdW5uaW5nIG9uIHBvcnQgJHtQT1JUfSAgICAgICAgICAgICAg4pWRCuKV
kSAgICAgICBTaGVsYnkgVGVzdG5ldCDinJMgICAgICAgICAgICAgICAgICAg4pWRCuKVkSAgICAg
ICBUdXJzbyBEQiDinJMgICAgICAgICAgICAgICAgICAgICAgICAg4pWRCuKVmuKVkOKVkOKVkOKV
kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV
kOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKV
kOKVnQogICAgYCk7CiAgfSk7Cn0KCm1haW4oKS5jYXRjaCgoZXJyKSA9PiB7IGNvbnNvbGUuZXJy
b3IoIkZhaWxlZCB0byBzdGFydDoiLCBlcnIpOyBwcm9jZXNzLmV4aXQoMSk7IH0pOwo=
B64_M0
verify "$TMPD/m0" "${NEW_MOD[0]}" "backend/src/index.ts"

base64 -d > "$TMPD/a0" <<'B64_A0' || die "backend/src/routes/mediaProbe.ts: base64 decode failed."
Ly8gc3JjL3JvdXRlcy9tZWRpYVByb2JlLnRzCi8vIHZtX21lZGlhX3Byb2JlOiBhIG1lYXN1cmVt
ZW50LCBub3QgYSBmZWF0dXJlLiBJdCBhbnN3ZXJzIG9uZSBxdWVzdGlvbgovLyBiZWZvcmUgdHJh
bnNjb2RpbmcgaXMgYnVpbHQ6IGNhbiBUSElTIHNlcnZlciBydW4gRkZtcGVnLCBhbmQgaG93IGZh
c3Q/Ci8vCi8vICAgR0VUIC9hcGkvaGVhbHRoL21lZGlhICAgICAgICAgIHdoYXQgdGhpcyBzZXJ2
ZXIgaXMsIGFuZCB0aGUgbGFzdCBydW4KLy8gICBHRVQgL2FwaS9oZWFsdGgvbWVkaWE/cnVuPTEg
ICAgc3RhcnQgYSBydW4gKG9uZSBhdCBhIHRpbWUsIGF0IG1vc3QKLy8gICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgb25lIGV2ZXJ5IDEwIG1pbnV0ZXMpLCB0aGVuIHNob3cgaXQKLy8K
Ly8gQSBydW4gbWFrZXMgaXRzIG93biB0ZXN0IHZpZGVvIChubyB1c2VyIGZpbGUgaXMgdG91Y2hl
ZCksIHRoZW4gZG9lcwovLyB0aGUgd29yayB0cmFuc2NvZGluZyB3b3VsZCBkbywgc21hbGxlc3Qg
Zmlyc3Q6IG9uZSBwaWN0dXJlLCBhIDM2MHAKLy8gc3RyZWFtLCBhIDcyMHAgKyAzNjBwIGxhZGRl
ciwgYSAxMDgwcCBzdHJlYW0uIEV2ZXJ5IHN0ZXAgaXMgd3JpdHRlbiB0bwovLyB0aGUgZGF0YWJh
c2UgQkVGT1JFIGl0IHN0YXJ0cywgc28gaWYgdGhlIHNlcnZlciBpcyBzdG9wcGVkIGZvciB1c2lu
ZwovLyB0b28gbXVjaCBtZW1vcnksIHRoZSBzdGVwIHRoYXQgZGlkIGl0IGlzIHN0aWxsIG9uIHJl
Y29yZC4KLy8KLy8gVGhpcyBmaWxlIGFuZCBpdHMgdGFibGUgKG1lZGlhX3Byb2JlX3N0ZXBzKSBh
cmUgcmVtb3ZlZCB3aGVuCi8vIHRyYW5zY29kaW5nIGl0c2VsZiBpcyBidWlsdC4KaW1wb3J0IHsg
Um91dGVyIH0gZnJvbSAiZXhwcmVzcyI7CmltcG9ydCB7IHNwYXduIH0gZnJvbSAiY2hpbGRfcHJv
Y2VzcyI7CmltcG9ydCBjcnlwdG8gZnJvbSAiY3J5cHRvIjsKaW1wb3J0IGZzIGZyb20gImZzL3By
b21pc2VzIjsKaW1wb3J0IG9zIGZyb20gIm9zIjsKaW1wb3J0IHBhdGggZnJvbSAicGF0aCI7Cmlt
cG9ydCB7IGdldERiIH0gZnJvbSAiLi4vbGliL2RiLmpzIjsKCmNvbnN0IHJvdXRlciA9IFJvdXRl
cigpOwoKY29uc3QgQ09PTERPV05fTVMgPSAxMCAqIDYwXzAwMDsKY29uc3QgU1RFUF9USU1FT1VU
X01TID0gNCAqIDYwXzAwMDsKY29uc3QgU09VUkNFX1NFQ09ORFMgPSAyMDsKY29uc3QgU09VUkNF
XzEwODBfU0VDT05EUyA9IDEwOwoKbGV0IHJ1bm5pbmc6IHN0cmluZyB8IG51bGwgPSBudWxsOyAg
ICAgIC8vIHJ1biBpZCwgd2hpbGUgYSBydW4gaXMgaW4gcHJvZ3Jlc3MgaW4gdGhpcyBwcm9jZXNz
CmxldCB0YWJsZVJlYWR5OiBQcm9taXNlPHZvaWQ+IHwgbnVsbCA9IG51bGw7CgpmdW5jdGlvbiBy
ZWFkeSgpOiBQcm9taXNlPHZvaWQ+IHsKICB0YWJsZVJlYWR5ID8/PSBnZXREYigpLmV4ZWN1dGUo
YENSRUFURSBUQUJMRSBJRiBOT1QgRVhJU1RTIG1lZGlhX3Byb2JlX3N0ZXBzICgKICAgIGlkICAg
ICAgICAgIElOVEVHRVIgUFJJTUFSWSBLRVkgQVVUT0lOQ1JFTUVOVCwKICAgIHJ1bl9pZCAgICAg
IFRFWFQgTk9UIE5VTEwsCiAgICBzdGVwICAgICAgICBURVhUIE5PVCBOVUxMLAogICAgc3RhdGUg
ICAgICAgVEVYVCBOT1QgTlVMTCwKICAgIGRldGFpbCAgICAgIFRFWFQsCiAgICBzdGFydGVkX2F0
ICBJTlRFR0VSIE5PVCBOVUxMLAogICAgZmluaXNoZWRfYXQgSU5URUdFUgogIClgKS50aGVuKCgp
ID0+IHVuZGVmaW5lZCkuY2F0Y2goKGVycikgPT4geyB0YWJsZVJlYWR5ID0gbnVsbDsgdGhyb3cg
ZXJyOyB9KTsKICByZXR1cm4gdGFibGVSZWFkeTsKfQoKLy8g4pSA4pSAIHJ1bm5pbmcgYSBjb21t
YW5kIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU
gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU
gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAoKaW50ZXJm
YWNlIFJhbiB7IGNvZGU6IG51bWJlciB8IG51bGw7IHNpZ25hbDogc3RyaW5nIHwgbnVsbDsgbXM6
IG51bWJlcjsgb3V0OiBzdHJpbmc7IGVycjogc3RyaW5nOyBwZWFrTWI6IG51bWJlciB8IG51bGw7
IHRpbWVkT3V0OiBib29sZWFuOyBtaXNzaW5nOiBib29sZWFuIH0KCi8qKiBIaWdoZXN0IG1lbW9y
eSB0aGUgcHJvY2VzcyBoYXMgdXNlZCBzbyBmYXIsIGluIE1CLiBMaW51eCBvbmx5LiAqLwphc3lu
YyBmdW5jdGlvbiBwZWFrT2YocGlkOiBudW1iZXIpOiBQcm9taXNlPG51bWJlciB8IG51bGw+IHsK
ICB0cnkgewogICAgY29uc3Qgc3RhdHVzID0gYXdhaXQgZnMucmVhZEZpbGUoYC9wcm9jLyR7cGlk
fS9zdGF0dXNgLCAidXRmOCIpOwogICAgY29uc3QgbSA9IC9WbUhXTTpccysoXGQrKVxzK2tCLy5l
eGVjKHN0YXR1cyk7CiAgICByZXR1cm4gbSA/IE1hdGgucm91bmQoTnVtYmVyKG1bMV0pIC8gMTAy
NCkgOiBudWxsOwogIH0gY2F0Y2ggeyByZXR1cm4gbnVsbDsgfQp9CgpmdW5jdGlvbiBydW4oY21k
OiBzdHJpbmcsIGFyZ3M6IHN0cmluZ1tdLCB0aW1lb3V0TXMgPSBTVEVQX1RJTUVPVVRfTVMpOiBQ
cm9taXNlPFJhbj4gewogIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgY29u
c3QgdDAgPSBEYXRlLm5vdygpOwogICAgbGV0IG91dCA9ICIiLCBlcnIgPSAiIiwgcGVha01iOiBu
dW1iZXIgfCBudWxsID0gbnVsbCwgdGltZWRPdXQgPSBmYWxzZSwgbWlzc2luZyA9IGZhbHNlLCBk
b25lID0gZmFsc2U7CiAgICBjb25zdCBjaGlsZCA9IHNwYXduKGNtZCwgYXJncywgeyBzdGRpbzog
WyJpZ25vcmUiLCAicGlwZSIsICJwaXBlIl0gfSk7CiAgICAvLyBUaGUgd2ViIHNlcnZlciBjb21l
cyBmaXJzdDogdGhlIG1lYXN1cmVtZW50IHJ1bnMgYXQgbG93IHByaW9yaXR5LgogICAgaWYgKGNo
aWxkLnBpZCkgeyB0cnkgeyBvcy5zZXRQcmlvcml0eShjaGlsZC5waWQsIDEwKTsgfSBjYXRjaCB7
fSB9CiAgICBjb25zdCBwb2xsID0gc2V0SW50ZXJ2YWwoYXN5bmMgKCkgPT4gewogICAgICBpZiAo
IWNoaWxkLnBpZCkgcmV0dXJuOwogICAgICBjb25zdCBwID0gYXdhaXQgcGVha09mKGNoaWxkLnBp
ZCk7CiAgICAgIGlmIChwICE9PSBudWxsICYmIChwZWFrTWIgPT09IG51bGwgfHwgcCA+IHBlYWtN
YikpIHBlYWtNYiA9IHA7CiAgICB9LCAyMDApOwogICAgY29uc3QgdGltZXIgPSBzZXRUaW1lb3V0
KCgpID0+IHsgdGltZWRPdXQgPSB0cnVlOyBjaGlsZC5raWxsKCJTSUdLSUxMIik7IH0sIHRpbWVv
dXRNcyk7CiAgICBjb25zdCBlbmQgPSAoY29kZTogbnVtYmVyIHwgbnVsbCwgc2lnbmFsOiBzdHJp
bmcgfCBudWxsKSA9PiB7CiAgICAgIGlmIChkb25lKSByZXR1cm47IGRvbmUgPSB0cnVlOwogICAg
ICBjbGVhckludGVydmFsKHBvbGwpOyBjbGVhclRpbWVvdXQodGltZXIpOwogICAgICByZXNvbHZl
KHsgY29kZSwgc2lnbmFsLCBtczogRGF0ZS5ub3coKSAtIHQwLCBvdXQsIGVycjogZXJyLnNsaWNl
KC0xNTAwKSwgcGVha01iLCB0aW1lZE91dCwgbWlzc2luZyB9KTsKICAgIH07CiAgICBjaGlsZC5z
dGRvdXQub24oImRhdGEiLCAoZCkgPT4geyBpZiAob3V0Lmxlbmd0aCA8IDIwMF8wMDApIG91dCAr
PSBkOyB9KTsKICAgIGNoaWxkLnN0ZGVyci5vbigiZGF0YSIsIChkKSA9PiB7IGVyciArPSBkOyBp
ZiAoZXJyLmxlbmd0aCA+IDIwXzAwMCkgZXJyID0gZXJyLnNsaWNlKC0xMF8wMDApOyB9KTsKICAg
IGNoaWxkLm9uKCJlcnJvciIsIChlOiBOb2RlSlMuRXJybm9FeGNlcHRpb24pID0+IHsgbWlzc2lu
ZyA9IGUuY29kZSA9PT0gIkVOT0VOVCI7IGVyciArPSBTdHJpbmcoZS5tZXNzYWdlKTsgZW5kKG51
bGwsIG51bGwpOyB9KTsKICAgIGNoaWxkLm9uKCJjbG9zZSIsIChjb2RlLCBzaWduYWwpID0+IGVu
ZChjb2RlLCBzaWduYWwpKTsKICB9KTsKfQoKLy8g4pSA4pSAIHdoYXQgdGhpcyBzZXJ2ZXIgaXMg
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgpjb25zdCByZWFkVGV4dCA9
IChwOiBzdHJpbmcpID0+IGZzLnJlYWRGaWxlKHAsICJ1dGY4IikudGhlbigocykgPT4gcy50cmlt
KCkpLmNhdGNoKCgpID0+IG51bGwpOwoKYXN5bmMgZnVuY3Rpb24gZW52aXJvbm1lbnQoKSB7CiAg
Y29uc3QgY3B1TWF4ID0gYXdhaXQgcmVhZFRleHQoIi9zeXMvZnMvY2dyb3VwL2NwdS5tYXgiKTsg
ICAgICAgICAgICAgICAgIC8vICI8cXVvdGE+IDxwZXJpb2Q+IiBvciAibWF4IDxwZXJpb2Q+Igog
IGNvbnN0IG1lbU1heCA9IGF3YWl0IHJlYWRUZXh0KCIvc3lzL2ZzL2Nncm91cC9tZW1vcnkubWF4
Iik7CiAgbGV0IGNwdUxpbWl0OiBudW1iZXIgfCBudWxsID0gbnVsbDsKICBpZiAoY3B1TWF4KSB7
CiAgICBjb25zdCBbcXVvdGEsIHBlcmlvZF0gPSBjcHVNYXguc3BsaXQoL1xzKy8pOwogICAgaWYg
KHF1b3RhICE9PSAibWF4IiAmJiBOdW1iZXIocGVyaW9kKSA+IDApIGNwdUxpbWl0ID0gTWF0aC5y
b3VuZCgoTnVtYmVyKHF1b3RhKSAvIE51bWJlcihwZXJpb2QpKSAqIDEwMCkgLyAxMDA7CiAgfQog
IGNvbnN0IG1lbUxpbWl0TWIgPSBtZW1NYXggJiYgbWVtTWF4ICE9PSAibWF4IiAmJiBOdW1iZXIo
bWVtTWF4KSA+IDAgPyBNYXRoLnJvdW5kKE51bWJlcihtZW1NYXgpIC8gMTA0ODU3NikgOiBudWxs
OwogIGxldCB0bXBGcmVlTWI6IG51bWJlciB8IG51bGwgPSBudWxsOwogIHRyeSB7CiAgICBjb25z
dCBzdCA9IGF3YWl0IChmcyBhcyBhbnkpLnN0YXRmcyhvcy50bXBkaXIoKSk7CiAgICB0bXBGcmVl
TWIgPSBNYXRoLnJvdW5kKChOdW1iZXIoc3QuYmF2YWlsKSAqIE51bWJlcihzdC5ic2l6ZSkpIC8g
MTA0ODU3Nik7CiAgfSBjYXRjaCB7fQogIHJldHVybiB7CiAgICBub2RlOiBwcm9jZXNzLnZlcnNp
b24sCiAgICBwbGF0Zm9ybTogYCR7b3MucGxhdGZvcm0oKX0gJHtvcy5hcmNoKCl9YCwKICAgIGNw
dXNWaXNpYmxlOiBvcy5jcHVzKCkubGVuZ3RoLAogICAgY3B1TW9kZWw6IG9zLmNwdXMoKVswXT8u
bW9kZWwgPz8gbnVsbCwKICAgIC8qKiBDUFVzIHRoaXMgc2VydmljZSBtYXkgYWN0dWFsbHkgdXNl
LiBudWxsIG1lYW5zIG5vIGxpbWl0IHdhcyBmb3VuZC4gKi8KICAgIGNwdUxpbWl0LAogICAgbWVt
b3J5VG90YWxNYjogTWF0aC5yb3VuZChvcy50b3RhbG1lbSgpIC8gMTA0ODU3NiksCiAgICAvKiog
TWVtb3J5IHRoaXMgc2VydmljZSBtYXkgdXNlIGJlZm9yZSBpdCBpcyBzdG9wcGVkLiBudWxsIG1l
YW5zIG5vIGxpbWl0IHdhcyBmb3VuZC4gKi8KICAgIG1lbW9yeUxpbWl0TWI6IG1lbUxpbWl0TWIs
CiAgICBzZXJ2ZXJNZW1vcnlOb3dNYjogTWF0aC5yb3VuZChwcm9jZXNzLm1lbW9yeVVzYWdlKCku
cnNzIC8gMTA0ODU3NiksCiAgICB0bXBEaXI6IG9zLnRtcGRpcigpLAogICAgdG1wRnJlZU1iLAog
ICAgb25SZW5kZXI6ICEhcHJvY2Vzcy5lbnYuUkVOREVSLAogICAgcmVuZGVyU2VydmljZVR5cGU6
IHByb2Nlc3MuZW52LlJFTkRFUl9TRVJWSUNFX1RZUEUgPz8gbnVsbCwKICAgIGNvbW1pdDogKHBy
b2Nlc3MuZW52LlJFTkRFUl9HSVRfQ09NTUlUID8/ICIiKS5zbGljZSgwLCA3KSB8fCBudWxsLAog
IH07Cn0KCi8vIOKUgOKUgCB0aGUgc3RlcHMg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA
4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgphc3luYyBmdW5jdGlvbiBk
aXJTdGF0cyhkaXI6IHN0cmluZyk6IFByb21pc2U8eyBmaWxlczogbnVtYmVyOyBrYjogbnVtYmVy
OyBuYW1lczogc3RyaW5nW10gfT4gewogIGxldCBmaWxlcyA9IDAsIGJ5dGVzID0gMDsgY29uc3Qg
bmFtZXM6IHN0cmluZ1tdID0gW107CiAgYXN5bmMgZnVuY3Rpb24gd2FsayhkOiBzdHJpbmcsIHJl
bDogc3RyaW5nKSB7CiAgICBmb3IgKGNvbnN0IGUgb2YgYXdhaXQgZnMucmVhZGRpcihkLCB7IHdp
dGhGaWxlVHlwZXM6IHRydWUgfSkpIHsKICAgICAgY29uc3QgcCA9IHBhdGguam9pbihkLCBlLm5h
bWUpLCByID0gcmVsID8gYCR7cmVsfS8ke2UubmFtZX1gIDogZS5uYW1lOwogICAgICBpZiAoZS5p
c0RpcmVjdG9yeSgpKSBhd2FpdCB3YWxrKHAsIHIpOwogICAgICBlbHNlIHsgZmlsZXMrKzsgYnl0
ZXMgKz0gKGF3YWl0IGZzLnN0YXQocCkpLnNpemU7IGlmIChuYW1lcy5sZW5ndGggPCAxMikgbmFt
ZXMucHVzaChyKTsgfQogICAgfQogIH0KICBhd2FpdCB3YWxrKGRpciwgIiIpLmNhdGNoKCgpID0+
IHt9KTsKICByZXR1cm4geyBmaWxlcywga2I6IE1hdGgucm91bmQoYnl0ZXMgLyAxMDI0KSwgbmFt
ZXMgfTsKfQoKLyoqIFdoYXQgYSBzdGVwIHJlcG9ydHMgYWJvdXQgYW4gRkZtcGVnIHJ1biBvdmVy
IGBzZWNvbmRzYCBvZiB2aWRlby4gKi8KZnVuY3Rpb24gbWVhc3VyZWQocjogUmFuLCBzZWNvbmRz
OiBudW1iZXIpIHsKICByZXR1cm4gewogICAgbXM6IHIubXMsCiAgICAvKiogYWJvdmUgMSBtZWFu
cyBmYXN0ZXIgdGhhbiB0aGUgdmlkZW8gcGxheXMgKi8KICAgIHNwZWVkOiByLm1zID4gMCA/IE1h
dGgucm91bmQoKHNlY29uZHMgLyAoci5tcyAvIDEwMDApKSAqIDEwMCkgLyAxMDAgOiBudWxsLAog
ICAgcGVha01lbW9yeU1iOiByLnBlYWtNYiwKICB9Owp9CgpjbGFzcyBTdGVwRmFpbGVkIGV4dGVu
ZHMgRXJyb3IgewogIGNvbnN0cnVjdG9yKG1lc3NhZ2U6IHN0cmluZywgcHVibGljIGRldGFpbDog
UmVjb3JkPHN0cmluZywgdW5rbm93bj4gPSB7fSkgeyBzdXBlcihtZXNzYWdlKTsgfQp9CgpmdW5j
dGlvbiBjaGVjayhyOiBSYW4sIHdoYXQ6IHN0cmluZykgewogIGlmIChyLm1pc3NpbmcpIHRocm93
IG5ldyBTdGVwRmFpbGVkKGAke3doYXR9OiB0aGUgcHJvZ3JhbSBpcyBub3QgaW5zdGFsbGVkIG9u
IHRoaXMgc2VydmVyLmApOwogIGlmIChyLnRpbWVkT3V0KSB0aHJvdyBuZXcgU3RlcEZhaWxlZChg
JHt3aGF0fTogc3RvcHBlZCBhZnRlciAke1NURVBfVElNRU9VVF9NUyAvIDYwXzAwMH0gbWludXRl
cyB3aXRob3V0IGZpbmlzaGluZy5gLCB7IG1zOiByLm1zLCBwZWFrTWVtb3J5TWI6IHIucGVha01i
IH0pOwogIC8vIEtpbGxlZCBmcm9tIG91dHNpZGUgd2l0aG91dCBvdXIgdGltZW91dDogb24gYSBz
bWFsbCBpbnN0YW5jZSB0aGlzIGlzIHRoZSBzeXN0ZW0gcmVjbGFpbWluZyBtZW1vcnkuCiAgaWYg
KHIuc2lnbmFsID09PSAiU0lHS0lMTCIpIHRocm93IG5ldyBTdGVwRmFpbGVkKGAke3doYXR9OiB0
aGUgc3lzdGVtIHN0b3BwZWQgRkZtcGVnLiBUaGF0IHVzdWFsbHkgbWVhbnMgaXQgdXNlZCBtb3Jl
IG1lbW9yeSB0aGFuIHRoaXMgc2VydmljZSBpcyBhbGxvd2VkLmAsIHsgbXM6IHIubXMsIHBlYWtN
ZW1vcnlNYjogci5wZWFrTWIgfSk7CiAgaWYgKHIuY29kZSAhPT0gMCkgdGhyb3cgbmV3IFN0ZXBG
YWlsZWQoYCR7d2hhdH06IGV4aXQgY29kZSAke3IuY29kZX0ke3Iuc2lnbmFsID8gYCwgc2lnbmFs
ICR7ci5zaWduYWx9YCA6ICIifS5gLCB7IG1zOiByLm1zLCBwZWFrTWVtb3J5TWI6IHIucGVha01i
LCBsYXN0T3V0cHV0OiByLmVyci5zbGljZSgtNjAwKSB9KTsKfQoKY29uc3QgWDI2NCA9IFsiLWM6
diIsICJsaWJ4MjY0IiwgIi1wcmVzZXQiLCAidmVyeWZhc3QiLCAiLXBpeF9mbXQiLCAieXV2NDIw
cCIsICItZyIsICIxMjAiLCAiLWtleWludF9taW4iLCAiMTIwIiwgIi1zY190aHJlc2hvbGQiLCAi
MCJdOwpjb25zdCBITFMgPSBbIi1mIiwgImhscyIsICItaGxzX3RpbWUiLCAiNCIsICItaGxzX3Bs
YXlsaXN0X3R5cGUiLCAidm9kIiwgIi1obHNfc2VnbWVudF90eXBlIiwgImZtcDQiLCAiLWhsc19m
bGFncyIsICJpbmRlcGVuZGVudF9zZWdtZW50cyJdOwoKdHlwZSBTdGVwID0geyBuYW1lOiBzdHJp
bmc7IHdoYXQ6IHN0cmluZzsgcnVuOiAoZGlyOiBzdHJpbmcpID0+IFByb21pc2U8UmVjb3JkPHN0
cmluZywgdW5rbm93bj4+IH07Cgpjb25zdCBTVEVQUzogU3RlcFtdID0gWwogIHsKICAgIG5hbWU6
ICJ0b29scyIsIHdoYXQ6ICJGRm1wZWcgYW5kIGZmcHJvYmUgYXJlIGluc3RhbGxlZCwgd2l0aCB0
aGUgZW5jb2RlcnMgYW5kIGZvcm1hdHMgdHJhbnNjb2RpbmcgbmVlZHMiLAogICAgcnVuOiBhc3lu
YyAoKSA9PiB7CiAgICAgIGNvbnN0IHYgPSBhd2FpdCBydW4oImZmbXBlZyIsIFsiLWhpZGVfYmFu
bmVyIiwgIi12ZXJzaW9uIl0sIDIwXzAwMCk7IGNoZWNrKHYsICJmZm1wZWcgLXZlcnNpb24iKTsK
ICAgICAgY29uc3QgcCA9IGF3YWl0IHJ1bigiZmZwcm9iZSIsIFsiLWhpZGVfYmFubmVyIiwgIi12
ZXJzaW9uIl0sIDIwXzAwMCk7CiAgICAgIGNvbnN0IGVuYyA9IGF3YWl0IHJ1bigiZmZtcGVnIiwg
WyItaGlkZV9iYW5uZXIiLCAiLWVuY29kZXJzIl0sIDIwXzAwMCk7CiAgICAgIGNvbnN0IG11eCA9
IGF3YWl0IHJ1bigiZmZtcGVnIiwgWyItaGlkZV9iYW5uZXIiLCAiLW11eGVycyJdLCAyMF8wMDAp
OwogICAgICBjb25zdCBwcm90byA9IGF3YWl0IHJ1bigiZmZtcGVnIiwgWyItaGlkZV9iYW5uZXIi
LCAiLXByb3RvY29scyJdLCAyMF8wMDApOwogICAgICBjb25zdCBoYXMgPSAodGV4dDogc3RyaW5n
LCByZTogUmVnRXhwKSA9PiByZS50ZXN0KHRleHQpOwogICAgICBjb25zdCByZXN1bHQgPSB7CiAg
ICAgICAgZmZtcGVnOiB2Lm91dC5zcGxpdCgiXG4iKVswXT8udHJpbSgpID8/IG51bGwsCiAgICAg
ICAgZmZwcm9iZTogcC5taXNzaW5nID8gbnVsbCA6IChwLm91dC5zcGxpdCgiXG4iKVswXT8udHJp
bSgpID8/IG51bGwpLAogICAgICAgIGxpYngyNjQ6IGhhcyhlbmMub3V0LCAvXGJsaWJ4MjY0XGIv
KSwKICAgICAgICBhYWM6IGhhcyhlbmMub3V0LCAvXlxzKkFcUypccythYWNcYi9tKSwKICAgICAg
ICBtanBlZzogaGFzKGVuYy5vdXQsIC9cYm1qcGVnXGIvKSwKICAgICAgICBobHNNdXhlcjogaGFz
KG11eC5vdXQsIC9cYmhsc1xiLyksCiAgICAgICAgLyoqIEZGbXBlZyBjYW4gcmVhZCBhIGZpbGUg
c3RyYWlnaHQgZnJvbSBzdG9yYWdlIG92ZXIgSFRUUFMgKi8KICAgICAgICBodHRwc0lucHV0OiBo
YXMocHJvdG8ub3V0LCAvXGJodHRwc1xiLyksCiAgICAgIH07CiAgICAgIGlmICghcmVzdWx0Lmxp
YngyNjQpIHRocm93IG5ldyBTdGVwRmFpbGVkKCJGRm1wZWcgaXMgaW5zdGFsbGVkIGJ1dCBoYXMg
bm8gSC4yNjQgZW5jb2RlciAobGlieDI2NCkuIiwgcmVzdWx0KTsKICAgICAgaWYgKCFyZXN1bHQu
aGxzTXV4ZXIpIHRocm93IG5ldyBTdGVwRmFpbGVkKCJGRm1wZWcgaXMgaW5zdGFsbGVkIGJ1dCBj
YW5ub3Qgd3JpdGUgSExTLiIsIHJlc3VsdCk7CiAgICAgIHJldHVybiByZXN1bHQ7CiAgICB9LAog
IH0sCiAgewogICAgbmFtZTogInNvdXJjZSIsIHdoYXQ6IGBtYWtlIGEgJHtTT1VSQ0VfU0VDT05E
U30gc2Vjb25kIDcyMHAgdGVzdCB2aWRlbyB3aXRoIHNvdW5kICh0aGUgc3RhbmQgaW4gZm9yIGFu
IHVwbG9hZClgLAogICAgcnVuOiBhc3luYyAoZGlyKSA9PiB7CiAgICAgIGNvbnN0IHIgPSBhd2Fp
dCBydW4oImZmbXBlZyIsIFsiLWhpZGVfYmFubmVyIiwgIi15IiwgIi1mIiwgImxhdmZpIiwgIi1p
IiwgYHRlc3RzcmMyPXNpemU9MTI4MHg3MjA6cmF0ZT0zMDpkdXJhdGlvbj0ke1NPVVJDRV9TRUNP
TkRTfWAsCiAgICAgICAgIi1mIiwgImxhdmZpIiwgIi1pIiwgYHNpbmU9ZnJlcXVlbmN5PTQ0MDpk
dXJhdGlvbj0ke1NPVVJDRV9TRUNPTkRTfWAsCiAgICAgICAgIi1jOnYiLCAibGlieDI2NCIsICIt
cHJlc2V0IiwgInVsdHJhZmFzdCIsICItcGl4X2ZtdCIsICJ5dXY0MjBwIiwgIi1jOmEiLCAiYWFj
IiwgIi1iOmEiLCAiMTI4ayIsIHBhdGguam9pbihkaXIsICJzb3VyY2UubXA0IildKTsKICAgICAg
Y2hlY2sociwgIm1ha2luZyB0aGUgdGVzdCB2aWRlbyIpOwogICAgICByZXR1cm4geyAuLi5tZWFz
dXJlZChyLCBTT1VSQ0VfU0VDT05EUyksIGtiOiBNYXRoLnJvdW5kKChhd2FpdCBmcy5zdGF0KHBh
dGguam9pbihkaXIsICJzb3VyY2UubXA0IikpKS5zaXplIC8gMTAyNCkgfTsKICAgIH0sCiAgfSwK
ICB7CiAgICBuYW1lOiAicHJvYmUiLCB3aGF0OiAicmVhZCB0aGUgbGVuZ3RoLCBzaXplIGFuZCBj
b2RlY3Mgb2YgYSB2aWRlbyAoZmZwcm9iZSkiLAogICAgcnVuOiBhc3luYyAoZGlyKSA9PiB7CiAg
ICAgIGNvbnN0IHIgPSBhd2FpdCBydW4oImZmcHJvYmUiLCBbIi12IiwgImVycm9yIiwgIi1wcmlu
dF9mb3JtYXQiLCAianNvbiIsICItc2hvd19mb3JtYXQiLCAiLXNob3dfc3RyZWFtcyIsIHBhdGgu
am9pbihkaXIsICJzb3VyY2UubXA0IildLCAzMF8wMDApOwogICAgICBjaGVjayhyLCAiZmZwcm9i
ZSIpOwogICAgICBjb25zdCBqID0gSlNPTi5wYXJzZShyLm91dCk7CiAgICAgIGNvbnN0IHZpZGVv
ID0gKGouc3RyZWFtcyA/PyBbXSkuZmluZCgoczogYW55KSA9PiBzLmNvZGVjX3R5cGUgPT09ICJ2
aWRlbyIpOwogICAgICByZXR1cm4geyBtczogci5tcywgZHVyYXRpb25TZWNvbmRzOiBOdW1iZXIo
ai5mb3JtYXQ/LmR1cmF0aW9uKSwgd2lkdGg6IHZpZGVvPy53aWR0aCwgaGVpZ2h0OiB2aWRlbz8u
aGVpZ2h0LCBjb2RlYzogdmlkZW8/LmNvZGVjX25hbWUgfTsKICAgIH0sCiAgfSwKICB7CiAgICBu
YW1lOiAidGh1bWJuYWlsIiwgd2hhdDogInRha2Ugb25lIHBpY3R1cmUgZnJvbSB0aGUgdmlkZW8g
Zm9yIGEgbGlicmFyeSBjYXJkIiwKICAgIHJ1bjogYXN5bmMgKGRpcikgPT4gewogICAgICBjb25z
dCByID0gYXdhaXQgcnVuKCJmZm1wZWciLCBbIi1oaWRlX2Jhbm5lciIsICIteSIsICItc3MiLCAi
NSIsICItaSIsIHBhdGguam9pbihkaXIsICJzb3VyY2UubXA0IiksICItZnJhbWVzOnYiLCAiMSIs
ICItdmYiLCAic2NhbGU9NjQwOi0yIiwgIi1xOnYiLCAiNCIsIHBhdGguam9pbihkaXIsICJ0aHVt
Yi5qcGciKV0sIDYwXzAwMCk7CiAgICAgIGNoZWNrKHIsICJ0YWtpbmcgYSBwaWN0dXJlIik7CiAg
ICAgIHJldHVybiB7IG1zOiByLm1zLCBwZWFrTWVtb3J5TWI6IHIucGVha01iLCBrYjogTWF0aC5y
b3VuZCgoYXdhaXQgZnMuc3RhdChwYXRoLmpvaW4oZGlyLCAidGh1bWIuanBnIikpKS5zaXplIC8g
MTAyNCkgfTsKICAgIH0sCiAgfSwKICB7CiAgICBuYW1lOiAiaGxzXzM2MHAiLCB3aGF0OiAidHVy
biB0aGUgdmlkZW8gaW50byBvbmUgMzYwcCBzdHJlYW0gKEhMUywgNCBzZWNvbmQgcGFydHMpIiwK
ICAgIHJ1bjogYXN5bmMgKGRpcikgPT4gewogICAgICBjb25zdCBvdXQgPSBwYXRoLmpvaW4oZGly
LCAiaDM2MCIpOyBhd2FpdCBmcy5ta2RpcihvdXQsIHsgcmVjdXJzaXZlOiB0cnVlIH0pOwogICAg
ICBjb25zdCByID0gYXdhaXQgcnVuKCJmZm1wZWciLCBbIi1oaWRlX2Jhbm5lciIsICIteSIsICIt
aSIsIHBhdGguam9pbihkaXIsICJzb3VyY2UubXA0IiksICItdmYiLCAic2NhbGU9LTI6MzYwIiwg
Li4uWDI2NCwgIi1iOnYiLCAiODAwayIsICItbWF4cmF0ZSIsICI4NTZrIiwgIi1idWZzaXplIiwg
IjEyMDBrIiwKICAgICAgICAiLWM6YSIsICJhYWMiLCAiLWI6YSIsICI5NmsiLCAuLi5ITFMsICIt
aGxzX3NlZ21lbnRfZmlsZW5hbWUiLCBwYXRoLmpvaW4ob3V0LCAic2VnXyUwM2QubTRzIiksIHBh
dGguam9pbihvdXQsICJwbGF5bGlzdC5tM3U4IildKTsKICAgICAgY2hlY2sociwgInRoZSAzNjBw
IHN0cmVhbSIpOwogICAgICByZXR1cm4geyAuLi5tZWFzdXJlZChyLCBTT1VSQ0VfU0VDT05EUyks
IG91dHB1dDogYXdhaXQgZGlyU3RhdHMob3V0KSB9OwogICAgfSwKICB9LAogIHsKICAgIG5hbWU6
ICJobHNfbGFkZGVyIiwgd2hhdDogInR1cm4gdGhlIHZpZGVvIGludG8gNzIwcCBhbmQgMzYwcCBz
dHJlYW1zIGluIG9uZSBnbywgd2l0aCBhIG1hc3RlciBwbGF5bGlzdCAod2hhdCBhIGxlY3R1cmUg
d291bGQgZ2V0KSIsCiAgICBydW46IGFzeW5jIChkaXIpID0+IHsKICAgICAgY29uc3Qgb3V0ID0g
cGF0aC5qb2luKGRpciwgImxhZGRlciIpOyBhd2FpdCBmcy5ta2RpcihvdXQsIHsgcmVjdXJzaXZl
OiB0cnVlIH0pOwogICAgICBjb25zdCByID0gYXdhaXQgcnVuKCJmZm1wZWciLCBbIi1oaWRlX2Jh
bm5lciIsICIteSIsICItaSIsIHBhdGguam9pbihkaXIsICJzb3VyY2UubXA0IiksCiAgICAgICAg
Ii1maWx0ZXJfY29tcGxleCIsICJbMDp2XXNwbGl0PTJbYV1bYl07W2Fdc2NhbGU9LTI6NzIwW3Y3
MjBdO1tiXXNjYWxlPS0yOjM2MFt2MzYwXSIsCiAgICAgICAgIi1tYXAiLCAiW3Y3MjBdIiwgIi1t
YXAiLCAiMDphIiwgIi1tYXAiLCAiW3YzNjBdIiwgIi1tYXAiLCAiMDphIiwKICAgICAgICAuLi5Y
MjY0LCAiLWI6djowIiwgIjI4MDBrIiwgIi1tYXhyYXRlOnY6MCIsICIyOTk2ayIsICItYnVmc2l6
ZTp2OjAiLCAiNDIwMGsiLCAiLWI6djoxIiwgIjgwMGsiLCAiLW1heHJhdGU6djoxIiwgIjg1Nmsi
LCAiLWJ1ZnNpemU6djoxIiwgIjEyMDBrIiwKICAgICAgICAiLWM6YSIsICJhYWMiLCAiLWI6YTow
IiwgIjEyOGsiLCAiLWI6YToxIiwgIjk2ayIsCiAgICAgICAgLi4uSExTLCAiLW1hc3Rlcl9wbF9u
YW1lIiwgIm1hc3Rlci5tM3U4IiwgIi12YXJfc3RyZWFtX21hcCIsICJ2OjAsYTowLG5hbWU6NzIw
cCB2OjEsYToxLG5hbWU6MzYwcCIsCiAgICAgICAgIi1obHNfc2VnbWVudF9maWxlbmFtZSIsIHBh
dGguam9pbihvdXQsICIldiIsICJzZWdfJTAzZC5tNHMiKSwgcGF0aC5qb2luKG91dCwgIiV2Iiwg
InBsYXlsaXN0Lm0zdTgiKV0pOwogICAgICBjaGVjayhyLCAidGhlIDcyMHAgYW5kIDM2MHAgbGFk
ZGVyIik7CiAgICAgIGNvbnN0IHN0YXRzID0gYXdhaXQgZGlyU3RhdHMob3V0KTsKICAgICAgY29u
c3QgbWFzdGVyID0gYXdhaXQgZnMucmVhZEZpbGUocGF0aC5qb2luKG91dCwgIm1hc3Rlci5tM3U4
IiksICJ1dGY4IikuY2F0Y2goKCkgPT4gIiIpOwogICAgICByZXR1cm4geyAuLi5tZWFzdXJlZChy
LCBTT1VSQ0VfU0VDT05EUyksIG91dHB1dDogc3RhdHMsIG1hc3Rlckxpc3RzQm90aDogLzcyMHBc
L3BsYXlsaXN0XC5tM3U4Ly50ZXN0KG1hc3RlcikgJiYgLzM2MHBcL3BsYXlsaXN0XC5tM3U4Ly50
ZXN0KG1hc3RlcikgfTsKICAgIH0sCiAgfSwKICB7CiAgICBuYW1lOiAiaGxzXzEwODBwIiwgd2hh
dDogYHR1cm4gJHtTT1VSQ0VfMTA4MF9TRUNPTkRTfSBzZWNvbmRzIG9mIDEwODBwIHZpZGVvIGlu
dG8gYSAxMDgwcCBzdHJlYW0gKHRoZSBoZWF2aWVzdCB0aGluZyB0cmFuc2NvZGluZyB3b3VsZCBk
bylgLAogICAgcnVuOiBhc3luYyAoZGlyKSA9PiB7CiAgICAgIGNvbnN0IHNyYyA9IHBhdGguam9p
bihkaXIsICJzb3VyY2UxMDgwLm1wNCIpOwogICAgICBjb25zdCBtYWtlID0gYXdhaXQgcnVuKCJm
Zm1wZWciLCBbIi1oaWRlX2Jhbm5lciIsICIteSIsICItZiIsICJsYXZmaSIsICItaSIsIGB0ZXN0
c3JjMj1zaXplPTE5MjB4MTA4MDpyYXRlPTMwOmR1cmF0aW9uPSR7U09VUkNFXzEwODBfU0VDT05E
U31gLAogICAgICAgICItZiIsICJsYXZmaSIsICItaSIsIGBzaW5lPWZyZXF1ZW5jeT00NDA6ZHVy
YXRpb249JHtTT1VSQ0VfMTA4MF9TRUNPTkRTfWAsCiAgICAgICAgIi1jOnYiLCAibGlieDI2NCIs
ICItcHJlc2V0IiwgInVsdHJhZmFzdCIsICItcGl4X2ZtdCIsICJ5dXY0MjBwIiwgIi1jOmEiLCAi
YWFjIiwgc3JjXSk7CiAgICAgIGNoZWNrKG1ha2UsICJtYWtpbmcgdGhlIDEwODBwIHRlc3Qgdmlk
ZW8iKTsKICAgICAgY29uc3Qgb3V0ID0gcGF0aC5qb2luKGRpciwgImgxMDgwIik7IGF3YWl0IGZz
Lm1rZGlyKG91dCwgeyByZWN1cnNpdmU6IHRydWUgfSk7CiAgICAgIGNvbnN0IHIgPSBhd2FpdCBy
dW4oImZmbXBlZyIsIFsiLWhpZGVfYmFubmVyIiwgIi15IiwgIi1pIiwgc3JjLCAuLi5YMjY0LCAi
LWI6diIsICI1MDAwayIsICItbWF4cmF0ZSIsICI1MzUwayIsICItYnVmc2l6ZSIsICI3NTAwayIs
CiAgICAgICAgIi1jOmEiLCAiYWFjIiwgIi1iOmEiLCAiMTI4ayIsIC4uLkhMUywgIi1obHNfc2Vn
bWVudF9maWxlbmFtZSIsIHBhdGguam9pbihvdXQsICJzZWdfJTAzZC5tNHMiKSwgcGF0aC5qb2lu
KG91dCwgInBsYXlsaXN0Lm0zdTgiKV0pOwogICAgICBjaGVjayhyLCAidGhlIDEwODBwIHN0cmVh
bSIpOwogICAgICByZXR1cm4geyAuLi5tZWFzdXJlZChyLCBTT1VSQ0VfMTA4MF9TRUNPTkRTKSwg
bWFrZVNvdXJjZU1zOiBtYWtlLm1zLCBvdXRwdXQ6IGF3YWl0IGRpclN0YXRzKG91dCkgfTsKICAg
IH0sCiAgfSwKXTsKCmFzeW5jIGZ1bmN0aW9uIGV4ZWN1dGUocnVuSWQ6IHN0cmluZykgewogIGNv
bnN0IGRiID0gZ2V0RGIoKTsKICAvLyBGb2xkZXJzIGxlZnQgYmVoaW5kIGJ5IGEgcnVuIHRoYXQg
d2FzIGN1dCBvZmYuCiAgZm9yIChjb25zdCBuYW1lIG9mIGF3YWl0IGZzLnJlYWRkaXIob3MudG1w
ZGlyKCkpLmNhdGNoKCgpID0+IFtdIGFzIHN0cmluZ1tdKSkgewogICAgaWYgKG5hbWUuc3RhcnRz
V2l0aCgidm0tbWVkaWEtcHJvYmUtIikpIGF3YWl0IGZzLnJtKHBhdGguam9pbihvcy50bXBkaXIo
KSwgbmFtZSksIHsgcmVjdXJzaXZlOiB0cnVlLCBmb3JjZTogdHJ1ZSB9KS5jYXRjaCgoKSA9PiB7
fSk7CiAgfQogIGNvbnN0IGRpciA9IGF3YWl0IGZzLm1rZHRlbXAocGF0aC5qb2luKG9zLnRtcGRp
cigpLCAidm0tbWVkaWEtcHJvYmUtIikpOwogIHRyeSB7CiAgICBmb3IgKGNvbnN0IHN0ZXAgb2Yg
U1RFUFMpIHsKICAgICAgY29uc3Qgc3RhcnRlZEF0ID0gRGF0ZS5ub3coKTsKICAgICAgY29uc3Qg
aW5zID0gYXdhaXQgZGIuZXhlY3V0ZSh7CiAgICAgICAgc3FsOiAiSU5TRVJUIElOVE8gbWVkaWFf
cHJvYmVfc3RlcHMgKHJ1bl9pZCwgc3RlcCwgc3RhdGUsIGRldGFpbCwgc3RhcnRlZF9hdCkgVkFM
VUVTICg/LCA/LCAnc3RhcnRlZCcsID8sID8pIiwKICAgICAgICBhcmdzOiBbcnVuSWQsIHN0ZXAu
bmFtZSwgSlNPTi5zdHJpbmdpZnkoeyB3aGF0OiBzdGVwLndoYXQgfSksIHN0YXJ0ZWRBdF0sCiAg
ICAgIH0pOwogICAgICBjb25zdCByb3dJZCA9IE51bWJlcihpbnMubGFzdEluc2VydFJvd2lkKTsK
ICAgICAgY29uc3QgZmluaXNoID0gKHN0YXRlOiBzdHJpbmcsIGRldGFpbDogUmVjb3JkPHN0cmlu
ZywgdW5rbm93bj4pID0+IGRiLmV4ZWN1dGUoewogICAgICAgIHNxbDogIlVQREFURSBtZWRpYV9w
cm9iZV9zdGVwcyBTRVQgc3RhdGUgPSA/LCBkZXRhaWwgPSA/LCBmaW5pc2hlZF9hdCA9ID8gV0hF
UkUgaWQgPSA/IiwKICAgICAgICBhcmdzOiBbc3RhdGUsIEpTT04uc3RyaW5naWZ5KHsgd2hhdDog
c3RlcC53aGF0LCAuLi5kZXRhaWwgfSksIERhdGUubm93KCksIHJvd0lkXSwKICAgICAgfSk7CiAg
ICAgIHRyeSB7CiAgICAgICAgYXdhaXQgZmluaXNoKCJkb25lIiwgYXdhaXQgc3RlcC5ydW4oZGly
KSk7CiAgICAgIH0gY2F0Y2ggKGVycjogYW55KSB7CiAgICAgICAgYXdhaXQgZmluaXNoKCJmYWls
ZWQiLCB7IGVycm9yOiBTdHJpbmcoZXJyPy5tZXNzYWdlID8/IGVyciksIC4uLihlcnIgaW5zdGFu
Y2VvZiBTdGVwRmFpbGVkID8gZXJyLmRldGFpbCA6IHt9KSB9KTsKICAgICAgICBjb25zb2xlLmVy
cm9yKGBbbWVkaWEgcHJvYmVdICR7c3RlcC5uYW1lfSBmYWlsZWQ6ICR7ZXJyPy5tZXNzYWdlID8/
IGVycn1gKTsKICAgICAgICBicmVhazsgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
Ly8gdGhlIHN0ZXBzIGFmdGVyIGl0IGFyZSBoZWF2aWVyOiBubyBwb2ludAogICAgICB9CiAgICB9
CiAgfSBmaW5hbGx5IHsKICAgIGF3YWl0IGZzLnJtKGRpciwgeyByZWN1cnNpdmU6IHRydWUsIGZv
cmNlOiB0cnVlIH0pLmNhdGNoKCgpID0+IHt9KTsKICB9Cn0KCi8vIOKUgOKUgCB0aGUgcmVwb3J0
IOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU
gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU
gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU
gOKUgOKUgOKUgAoKYXN5bmMgZnVuY3Rpb24gbGFzdFJ1bigpIHsKICBjb25zdCBkYiA9IGdldERi
KCk7CiAgY29uc3QgaGVhZCA9IGF3YWl0IGRiLmV4ZWN1dGUoIlNFTEVDVCBydW5faWQsIE1JTihz
dGFydGVkX2F0KSBBUyBzdGFydGVkX2F0IEZST00gbWVkaWFfcHJvYmVfc3RlcHMgR1JPVVAgQlkg
cnVuX2lkIE9SREVSIEJZIHN0YXJ0ZWRfYXQgREVTQyBMSU1JVCAxIik7CiAgaWYgKCFoZWFkLnJv
d3MubGVuZ3RoKSByZXR1cm4gbnVsbDsKICBjb25zdCBydW5JZCA9IFN0cmluZygoaGVhZC5yb3dz
WzBdIGFzIGFueSkucnVuX2lkKTsKICBjb25zdCByb3dzID0gYXdhaXQgZGIuZXhlY3V0ZSh7IHNx
bDogIlNFTEVDVCBzdGVwLCBzdGF0ZSwgZGV0YWlsLCBzdGFydGVkX2F0LCBmaW5pc2hlZF9hdCBG
Uk9NIG1lZGlhX3Byb2JlX3N0ZXBzIFdIRVJFIHJ1bl9pZCA9ID8gT1JERVIgQlkgaWQiLCBhcmdz
OiBbcnVuSWRdIH0pOwogIGNvbnN0IGluVGhpc1Byb2Nlc3MgPSBydW5uaW5nID09PSBydW5JZDsK
ICBjb25zdCBzdGVwcyA9IHJvd3Mucm93cy5tYXAoKHI6IGFueSkgPT4gewogICAgbGV0IGRldGFp
bDogUmVjb3JkPHN0cmluZywgdW5rbm93bj4gPSB7fTsKICAgIHRyeSB7IGRldGFpbCA9IEpTT04u
cGFyc2UoU3RyaW5nKHIuZGV0YWlsID8/ICJ7fSIpKTsgfSBjYXRjaCB7fQogICAgbGV0IHN0YXRl
ID0gU3RyaW5nKHIuc3RhdGUpOwogICAgLy8gInN0YXJ0ZWQiIHdpdGggbm9ib2R5IHdvcmtpbmcg
b24gaXQ6IHRoZSBzZXJ2ZXIgd2VudCBhd2F5IG1pZCBzdGVwLgogICAgaWYgKHN0YXRlID09PSAi
c3RhcnRlZCIgJiYgIWluVGhpc1Byb2Nlc3MpIHN0YXRlID0gImludGVycnVwdGVkIjsKICAgIHJl
dHVybiB7IHN0ZXA6IFN0cmluZyhyLnN0ZXApLCBzdGF0ZSwgLi4uZGV0YWlsIH07CiAgfSk7CiAg
Y29uc3QgaW50ZXJydXB0ZWQgPSBzdGVwcy5maW5kKChzKSA9PiBzLnN0YXRlID09PSAiaW50ZXJy
dXB0ZWQiKTsKICByZXR1cm4gewogICAgcnVuSWQsIHN0YXJ0ZWRBdDogbmV3IERhdGUoTnVtYmVy
KChoZWFkLnJvd3NbMF0gYXMgYW55KS5zdGFydGVkX2F0KSkudG9JU09TdHJpbmcoKSwKICAgIHN0
YXJ0ZWRBdE1zOiBOdW1iZXIoKGhlYWQucm93c1swXSBhcyBhbnkpLnN0YXJ0ZWRfYXQpLAogICAg
c3RhdGU6IGluVGhpc1Byb2Nlc3MgPyAicnVubmluZyIgOiBpbnRlcnJ1cHRlZCA/ICJpbnRlcnJ1
cHRlZCIgOiBzdGVwcy5zb21lKChzKSA9PiBzLnN0YXRlID09PSAiZmFpbGVkIikgPyAiZmFpbGVk
IiA6IHN0ZXBzLmxlbmd0aCA9PT0gU1RFUFMubGVuZ3RoID8gImNvbXBsZXRlIiA6ICJzdG9wcGVk
IGVhcmx5IiwKICAgIG5vdGU6IGludGVycnVwdGVkCiAgICAgID8gYFRoZSBzZXJ2ZXIgc3RvcHBl
ZCB3aGlsZSAiJHtpbnRlcnJ1cHRlZC5zdGVwfSIgd2FzIHJ1bm5pbmcuIE9uIGEgc21hbGwgaW5z
dGFuY2UgdGhhdCB1c3VhbGx5IG1lYW5zIHRoZSBzdGVwIHVzZWQgbW9yZSBtZW1vcnkgdGhhbiB0
aGUgc2VydmljZSBpcyBhbGxvd2VkLmAKICAgICAgOiB1bmRlZmluZWQsCiAgICBzdGVwc1BsYW5u
ZWQ6IFNURVBTLm1hcCgocykgPT4gcy5uYW1lKSwKICAgIHN0ZXBzLAogIH07Cn0KCnJvdXRlci5n
ZXQoIi8iLCBhc3luYyAocmVxLCByZXMpID0+IHsKICB0cnkgewogICAgYXdhaXQgcmVhZHkoKTsK
ICAgIGxldCBtZXNzYWdlID0gIkFkZCA/cnVuPTEgdG8gdGhpcyBhZGRyZXNzIHRvIHN0YXJ0IGEg
cnVuLiBJdCB0YWtlcyBvbmUgdG8gdGVuIG1pbnV0ZXMuIFRoZW4gcmVsb2FkIHRoaXMgYWRkcmVz
cyB3aXRob3V0ID9ydW49MSB0byBmb2xsb3cgaXQuIjsKICAgIGxldCBsYXN0ID0gYXdhaXQgbGFz
dFJ1bigpOwoKICAgIGlmIChyZXEucXVlcnkucnVuICE9PSB1bmRlZmluZWQpIHsKICAgICAgY29u
c3Qgc2luY2VMYXN0ID0gbGFzdCA/IERhdGUubm93KCkgLSBsYXN0LnN0YXJ0ZWRBdE1zIDogSW5m
aW5pdHk7CiAgICAgIGlmIChydW5uaW5nKSBtZXNzYWdlID0gIkEgcnVuIGlzIGluIHByb2dyZXNz
LiBSZWxvYWQgdG8gZm9sbG93IGl0LiI7CiAgICAgIGVsc2UgaWYgKHNpbmNlTGFzdCA8IENPT0xE
T1dOX01TKSB7CiAgICAgICAgbWVzc2FnZSA9IGBUaGUgbGFzdCBydW4gc3RhcnRlZCAke01hdGgu
cm91bmQoc2luY2VMYXN0IC8gNjBfMDAwKX0gbWludXRlKHMpIGFnby4gQSBuZXcgb25lIGNhbiBi
ZSBzdGFydGVkICR7TWF0aC5jZWlsKChDT09MRE9XTl9NUyAtIHNpbmNlTGFzdCkgLyA2MF8wMDAp
fSBtaW51dGUocykgZnJvbSBub3cuIEl0cyByZXN1bHQgaXMgYmVsb3cuYDsKICAgICAgfSBlbHNl
IHsKICAgICAgICBjb25zdCBydW5JZCA9IGNyeXB0by5yYW5kb21VVUlEKCk7CiAgICAgICAgcnVu
bmluZyA9IHJ1bklkOwogICAgICAgIGV4ZWN1dGUocnVuSWQpCiAgICAgICAgICAuY2F0Y2goKGVy
cikgPT4gY29uc29sZS5lcnJvcihgW21lZGlhIHByb2JlXSBydW4gZmFpbGVkOiAke2Vycj8ubWVz
c2FnZSA/PyBlcnJ9YCkpCiAgICAgICAgICAuZmluYWxseSgoKSA9PiB7IHJ1bm5pbmcgPSBudWxs
OyB9KTsKICAgICAgICBtZXNzYWdlID0gIlJ1biBzdGFydGVkLiBSZWxvYWQgdGhpcyBhZGRyZXNz
IGluIGEgbWludXRlIHRvIGZvbGxvdyBpdC4iOwogICAgICAgIC8vIEdpdmUgdGhlIGZpcnN0IHN0
ZXAgYSBtb21lbnQgdG8gYmUgd3JpdHRlbiwgc28gdGhpcyBhbnN3ZXIgYWxyZWFkeSBzaG93cyB0
aGUgcnVuLgogICAgICAgIGF3YWl0IG5ldyBQcm9taXNlKChyKSA9PiBzZXRUaW1lb3V0KHIsIDQw
MCkpOwogICAgICAgIGxhc3QgPSBhd2FpdCBsYXN0UnVuKCk7CiAgICAgIH0KICAgIH0gZWxzZSBp
ZiAocnVubmluZykgbWVzc2FnZSA9ICJBIHJ1biBpcyBpbiBwcm9ncmVzcy4gUmVsb2FkIHRvIGZv
bGxvdyBpdC4iOwogICAgZWxzZSBpZiAobGFzdCkgbWVzc2FnZSA9ICJSZXN1bHQgb2YgdGhlIGxh
c3QgcnVuIGlzIGJlbG93LiBBZGQgP3J1bj0xIHRvIHJ1biBhZ2FpbiAoYXQgbW9zdCBvbmNlIGV2
ZXJ5IDEwIG1pbnV0ZXMpLiI7CgogICAgcmVzLnNldEhlYWRlcigiQ2FjaGUtQ29udHJvbCIsICJu
by1zdG9yZSIpOwogICAgY29uc3QgeyBzdGFydGVkQXRNczogX2Ryb3AsIC4uLmxhc3RPdXQgfSA9
IGxhc3QgPz8gKHt9IGFzIGFueSk7CiAgICByZXR1cm4gcmVzLmpzb24oeyBwcm9iZTogIm1lZGlh
IiwgbWVzc2FnZSwgZW52aXJvbm1lbnQ6IGF3YWl0IGVudmlyb25tZW50KCksIGxhc3RSdW46IGxh
c3QgPyBsYXN0T3V0IDogbnVsbCB9KTsKICB9IGNhdGNoIChlcnI6IGFueSkgewogICAgcmV0dXJu
IHJlcy5zdGF0dXMoNTAwKS5qc29uKHsgZXJyb3I6IGBUaGUgbWVkaWEgcHJvYmUgaGl0IGEgcHJv
YmxlbTogJHtlcnI/Lm1lc3NhZ2UgPz8gZXJyfWAgfSk7CiAgfQp9KTsKCmV4cG9ydCBkZWZhdWx0
IHJvdXRlcjsK
B64_A0
verify "$TMPD/a0" "${NEW_ADD[0]}" "backend/src/routes/mediaProbe.ts"

grep -q "$MARKER" "$TMPD/a0"                 || die "mediaProbe.ts payload missing marker. Aborting."
grep -q '/api/health/media' "$TMPD/m0"       || die "index.ts payload does not mount the probe. Aborting."
grep -q '/api/collections' "$TMPD/m0"        || die "index.ts payload lost the collection routes. Aborting."
grep -q '/api/uploads' "$TMPD/m0"            || die "index.ts payload lost the upload routes. Aborting."
grep -q 'checkStorage' "$TMPD/m0"            || die "index.ts payload lost the storage check. Aborting."
say "2 payloads decoded and verified."

# ---- backups ----
mkdir -p "$BAKDIR/$STAMP"
for f in "${MOD[@]}"; do cp "$f" "$BAKDIR/$STAMP/$(bname "$f")"; done
for f in "${ADD[@]}"; do if [ -f "$f" ]; then cp "$f" "$BAKDIR/$STAMP/$(bname "$f")"; fi; done
say "Backups saved to $BAKDIR/$STAMP/"

rollback() {
  restore_from "$BAKDIR/$STAMP"
  die "$1 All files restored from $BAKDIR/$STAMP."
}

# ---- write ----
i=0; for f in "${ADD[@]}"; do mkdir -p "$(dirname "$f")"; cp "$TMPD/a$i" "$f" || rollback "Could not write $f."; i=$((i+1)); done
i=0; for f in "${MOD[@]}"; do cp "$TMPD/m$i" "$f" || rollback "Could not write $f."; i=$((i+1)); done

i=0; for f in "${ADD[@]}"; do [ "$(sha "$f")" = "${NEW_ADD[$i]}" ] || rollback "$f write verify failed."; i=$((i+1)); done
i=0; for f in "${MOD[@]}"; do [ "$(sha "$f")" = "${NEW_MOD[$i]}" ] || rollback "$f write verify failed."; i=$((i+1)); done

say "Applied the media probe (rebuild Part 3c, step 1)."
say "Verify before pushing:"
say "  (cd backend && npx tsc --noEmit)"
say "Undo: ./vm_media_probe.sh --revert"
say ""
say "After Render has deployed, open this address in a browser, wait two minutes,"
say "then open it again without ?run=1 and send me what it shows:"
say "  https://videomind-rebuild.onrender.com/api/health/media?run=1"
