// src/lib/exports.ts
// Generate downloadable transcript formats entirely in the browser.

export interface Segment { start: number; end: number; text: string; }

interface ExportVideo {
  title: string;
  summary?: string;
  chapters?: Array<{ title: string; startSeconds: number; summary: string }>;
  highlights?: Array<{ startSeconds: number; endSeconds: number; reason: string; text: string }>;
  tags?: string[];
  transcript?: Segment[];
}

// ── Time formatters ─────────────────────────────────────────────────────────
function pad(n: number, size = 2) { return String(Math.floor(n)).padStart(size, "0"); }

/** 00:01:23,456 — SRT uses a comma before milliseconds */
function srtTime(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec - Math.floor(sec)) * 1000);
  return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms, 3)}`;
}

/** 00:01:23.456 — WebVTT uses a period before milliseconds */
function vttTime(sec: number): string {
  return srtTime(sec).replace(",", ".");
}

/** 1:23 — human readable */
export function readableTime(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${pad(s)}`;
}

// ── Format builders ─────────────────────────────────────────────────────────

export function toSRT(segments: Segment[]): string {
  return segments
    .map((seg, i) =>
      `${i + 1}\n${srtTime(seg.start)} --> ${srtTime(seg.end)}\n${seg.text}\n`
    )
    .join("\n");
}

export function toVTT(segments: Segment[]): string {
  const body = segments
    .map((seg) => `${vttTime(seg.start)} --> ${vttTime(seg.end)}\n${seg.text}\n`)
    .join("\n");
  return `WEBVTT\n\n${body}`;
}

export function toMarkdown(video: ExportVideo): string {
  const lines: string[] = [];

  lines.push(`# ${video.title}\n`);

  if (video.tags?.length) {
    lines.push(`**Tags:** ${video.tags.join(", ")}\n`);
  }

  if (video.summary) {
    lines.push(`## Summary\n\n${video.summary}\n`);
  }

  if (video.chapters?.length) {
    lines.push(`## Chapters\n`);
    video.chapters.forEach((ch, i) => {
      lines.push(`### ${i + 1}. ${ch.title} — \`${readableTime(ch.startSeconds)}\`\n`);
      lines.push(`${ch.summary}\n`);
    });
  }

  if (video.highlights?.length) {
    lines.push(`## Highlights\n`);
    video.highlights.forEach((hl) => {
      lines.push(`> **${hl.reason}** — \`${readableTime(hl.startSeconds)}\``);
      lines.push(`>`);
      lines.push(`> ${hl.text}\n`);
    });
  }

  if (video.transcript?.length) {
    lines.push(`## Full Transcript\n`);
    video.transcript.forEach((seg) => {
      lines.push(`\`${readableTime(seg.start)}\` ${seg.text}`);
    });
    lines.push("");
  }

  lines.push(`---\n`);
  lines.push(`*Generated by [VideoMind](https://vidzmind.xyz) — AI video intelligence on Shelby Protocol*`);

  return lines.join("\n");
}

export function toPlainText(segments: Segment[]): string {
  return segments.map((s) => s.text).join(" ");
}

// ── Download trigger ────────────────────────────────────────────────────────
export function downloadFile(content: string, filename: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Slugify a title for use as a filename */
export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "transcript";
}
